/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountDetails200ResponseAvatar } from './accountDetails200ResponseAvatar';

export class AccountDetails200Response {
    'avatar'?: AccountDetails200ResponseAvatar;
    'id'?: number = 0;
    'iso_639_1'?: string;
    'iso_3166_1'?: string;
    'name'?: string;
    'include_adult'?: boolean = true;
    'username'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "avatar",
            "baseName": "avatar",
            "type": "AccountDetails200ResponseAvatar"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "iso_639_1",
            "baseName": "iso_639_1",
            "type": "string"
        },
        {
            "name": "iso_3166_1",
            "baseName": "iso_3166_1",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "include_adult",
            "baseName": "include_adult",
            "type": "boolean"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountDetails200Response.attributeTypeMap;
    }
}

