/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountWatchlistTv200ResponseResultsInner {
    'adult'?: boolean = true;
    'backdrop_path'?: string;
    'genre_ids'?: Array<number>;
    'id'?: number = 0;
    'origin_country'?: Array<string>;
    'original_language'?: string;
    'original_name'?: string;
    'overview'?: string;
    'popularity'?: number = 0;
    'poster_path'?: string;
    'first_air_date'?: string;
    'name'?: string;
    'vote_average'?: number = 0;
    'vote_count'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "adult",
            "baseName": "adult",
            "type": "boolean"
        },
        {
            "name": "backdrop_path",
            "baseName": "backdrop_path",
            "type": "string"
        },
        {
            "name": "genre_ids",
            "baseName": "genre_ids",
            "type": "Array<number>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "origin_country",
            "baseName": "origin_country",
            "type": "Array<string>"
        },
        {
            "name": "original_language",
            "baseName": "original_language",
            "type": "string"
        },
        {
            "name": "original_name",
            "baseName": "original_name",
            "type": "string"
        },
        {
            "name": "overview",
            "baseName": "overview",
            "type": "string"
        },
        {
            "name": "popularity",
            "baseName": "popularity",
            "type": "number"
        },
        {
            "name": "poster_path",
            "baseName": "poster_path",
            "type": "string"
        },
        {
            "name": "first_air_date",
            "baseName": "first_air_date",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "vote_average",
            "baseName": "vote_average",
            "type": "number"
        },
        {
            "name": "vote_count",
            "baseName": "vote_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AccountWatchlistTv200ResponseResultsInner.attributeTypeMap;
    }
}

