/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AlternativeNamesCopy200ResponseLogosInner } from './alternativeNamesCopy200ResponseLogosInner';

export class AlternativeNamesCopy200Response {
    'id'?: number = 0;
    'logos'?: Array<AlternativeNamesCopy200ResponseLogosInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "logos",
            "baseName": "logos",
            "type": "Array<AlternativeNamesCopy200ResponseLogosInner>"
        }    ];

    static getAttributeTypeMap() {
        return AlternativeNamesCopy200Response.attributeTypeMap;
    }
}

