/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AuthenticationCreateGuestSession200Response {
    'success'?: boolean = true;
    'guest_session_id'?: string;
    'expires_at'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean"
        },
        {
            "name": "guest_session_id",
            "baseName": "guest_session_id",
            "type": "string"
        },
        {
            "name": "expires_at",
            "baseName": "expires_at",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AuthenticationCreateGuestSession200Response.attributeTypeMap;
    }
}

