/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CertificationMovieList200ResponseCertificationsCAQCInner } from './certificationMovieList200ResponseCertificationsCAQCInner';
import { CertificationMovieList200ResponseCertificationsPRInner } from './certificationMovieList200ResponseCertificationsPRInner';
import { CertificationsTvList200ResponseCertificationsARInner } from './certificationsTvList200ResponseCertificationsARInner';
import { CertificationsTvList200ResponseCertificationsAUInner } from './certificationsTvList200ResponseCertificationsAUInner';
import { CertificationsTvList200ResponseCertificationsBGInner } from './certificationsTvList200ResponseCertificationsBGInner';
import { CertificationsTvList200ResponseCertificationsBRInner } from './certificationsTvList200ResponseCertificationsBRInner';
import { CertificationsTvList200ResponseCertificationsCAInner } from './certificationsTvList200ResponseCertificationsCAInner';
import { CertificationsTvList200ResponseCertificationsCAQCInner } from './certificationsTvList200ResponseCertificationsCAQCInner';
import { CertificationsTvList200ResponseCertificationsDEInner } from './certificationsTvList200ResponseCertificationsDEInner';
import { CertificationsTvList200ResponseCertificationsDKInner } from './certificationsTvList200ResponseCertificationsDKInner';
import { CertificationsTvList200ResponseCertificationsFIInner } from './certificationsTvList200ResponseCertificationsFIInner';
import { CertificationsTvList200ResponseCertificationsGBInner } from './certificationsTvList200ResponseCertificationsGBInner';
import { CertificationsTvList200ResponseCertificationsGRInner } from './certificationsTvList200ResponseCertificationsGRInner';
import { CertificationsTvList200ResponseCertificationsHUInner } from './certificationsTvList200ResponseCertificationsHUInner';
import { CertificationsTvList200ResponseCertificationsIDInner } from './certificationsTvList200ResponseCertificationsIDInner';
import { CertificationsTvList200ResponseCertificationsILInner } from './certificationsTvList200ResponseCertificationsILInner';
import { CertificationsTvList200ResponseCertificationsINInner } from './certificationsTvList200ResponseCertificationsINInner';
import { CertificationsTvList200ResponseCertificationsITInner } from './certificationsTvList200ResponseCertificationsITInner';
import { CertificationsTvList200ResponseCertificationsKRInner } from './certificationsTvList200ResponseCertificationsKRInner';
import { CertificationsTvList200ResponseCertificationsLTInner } from './certificationsTvList200ResponseCertificationsLTInner';
import { CertificationsTvList200ResponseCertificationsMAInner } from './certificationsTvList200ResponseCertificationsMAInner';
import { CertificationsTvList200ResponseCertificationsMXInner } from './certificationsTvList200ResponseCertificationsMXInner';
import { CertificationsTvList200ResponseCertificationsMYInner } from './certificationsTvList200ResponseCertificationsMYInner';
import { CertificationsTvList200ResponseCertificationsNOInner } from './certificationsTvList200ResponseCertificationsNOInner';
import { CertificationsTvList200ResponseCertificationsNZInner } from './certificationsTvList200ResponseCertificationsNZInner';
import { CertificationsTvList200ResponseCertificationsPLInner } from './certificationsTvList200ResponseCertificationsPLInner';
import { CertificationsTvList200ResponseCertificationsPRInner } from './certificationsTvList200ResponseCertificationsPRInner';
import { CertificationsTvList200ResponseCertificationsPTInner } from './certificationsTvList200ResponseCertificationsPTInner';
import { CertificationsTvList200ResponseCertificationsRUInner } from './certificationsTvList200ResponseCertificationsRUInner';
import { CertificationsTvList200ResponseCertificationsSEInner } from './certificationsTvList200ResponseCertificationsSEInner';
import { CertificationsTvList200ResponseCertificationsTHInner } from './certificationsTvList200ResponseCertificationsTHInner';
import { CertificationsTvList200ResponseCertificationsTRInner } from './certificationsTvList200ResponseCertificationsTRInner';
import { CertificationsTvList200ResponseCertificationsTWInner } from './certificationsTvList200ResponseCertificationsTWInner';
import { CertificationsTvList200ResponseCertificationsUSInner } from './certificationsTvList200ResponseCertificationsUSInner';
import { CertificationsTvList200ResponseCertificationsZAInner } from './certificationsTvList200ResponseCertificationsZAInner';

export class CertificationsTvList200ResponseCertifications {
    'AU'?: Array<CertificationsTvList200ResponseCertificationsAUInner>;
    'BR'?: Array<CertificationsTvList200ResponseCertificationsBRInner>;
    'CA'?: Array<CertificationsTvList200ResponseCertificationsCAInner>;
    'CA_QC'?: Array<CertificationsTvList200ResponseCertificationsCAQCInner>;
    'DE'?: Array<CertificationsTvList200ResponseCertificationsDEInner>;
    'ES'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'FR'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'GB'?: Array<CertificationsTvList200ResponseCertificationsGBInner>;
    'HU'?: Array<CertificationsTvList200ResponseCertificationsHUInner>;
    'KR'?: Array<CertificationsTvList200ResponseCertificationsKRInner>;
    'LT'?: Array<CertificationsTvList200ResponseCertificationsLTInner>;
    'NL'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'PH'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'PT'?: Array<CertificationsTvList200ResponseCertificationsPTInner>;
    'RU'?: Array<CertificationsTvList200ResponseCertificationsRUInner>;
    'SK'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'TH'?: Array<CertificationsTvList200ResponseCertificationsTHInner>;
    'US'?: Array<CertificationsTvList200ResponseCertificationsUSInner>;
    'IT'?: Array<CertificationsTvList200ResponseCertificationsITInner>;
    'FI'?: Array<CertificationsTvList200ResponseCertificationsFIInner>;
    'MY'?: Array<CertificationsTvList200ResponseCertificationsMYInner>;
    'NZ'?: Array<CertificationsTvList200ResponseCertificationsNZInner>;
    'NO'?: Array<CertificationsTvList200ResponseCertificationsNOInner>;
    'BG'?: Array<CertificationsTvList200ResponseCertificationsBGInner>;
    'MX'?: Array<CertificationsTvList200ResponseCertificationsMXInner>;
    'IN'?: Array<CertificationsTvList200ResponseCertificationsINInner>;
    'DK'?: Array<CertificationsTvList200ResponseCertificationsDKInner>;
    'SE'?: Array<CertificationsTvList200ResponseCertificationsSEInner>;
    'ID'?: Array<CertificationsTvList200ResponseCertificationsIDInner>;
    'TR'?: Array<CertificationsTvList200ResponseCertificationsTRInner>;
    'AR'?: Array<CertificationsTvList200ResponseCertificationsARInner>;
    'PL'?: Array<CertificationsTvList200ResponseCertificationsPLInner>;
    'MA'?: Array<CertificationsTvList200ResponseCertificationsMAInner>;
    'GR'?: Array<CertificationsTvList200ResponseCertificationsGRInner>;
    'IL'?: Array<CertificationsTvList200ResponseCertificationsILInner>;
    'TW'?: Array<CertificationsTvList200ResponseCertificationsTWInner>;
    'ZA'?: Array<CertificationsTvList200ResponseCertificationsZAInner>;
    'SG'?: Array<CertificationMovieList200ResponseCertificationsPRInner>;
    'PR'?: Array<CertificationsTvList200ResponseCertificationsPRInner>;
    'VI'?: Array<CertificationsTvList200ResponseCertificationsPRInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "AU",
            "baseName": "AU",
            "type": "Array<CertificationsTvList200ResponseCertificationsAUInner>"
        },
        {
            "name": "BR",
            "baseName": "BR",
            "type": "Array<CertificationsTvList200ResponseCertificationsBRInner>"
        },
        {
            "name": "CA",
            "baseName": "CA",
            "type": "Array<CertificationsTvList200ResponseCertificationsCAInner>"
        },
        {
            "name": "CA_QC",
            "baseName": "CA-QC",
            "type": "Array<CertificationsTvList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "DE",
            "baseName": "DE",
            "type": "Array<CertificationsTvList200ResponseCertificationsDEInner>"
        },
        {
            "name": "ES",
            "baseName": "ES",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "FR",
            "baseName": "FR",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "GB",
            "baseName": "GB",
            "type": "Array<CertificationsTvList200ResponseCertificationsGBInner>"
        },
        {
            "name": "HU",
            "baseName": "HU",
            "type": "Array<CertificationsTvList200ResponseCertificationsHUInner>"
        },
        {
            "name": "KR",
            "baseName": "KR",
            "type": "Array<CertificationsTvList200ResponseCertificationsKRInner>"
        },
        {
            "name": "LT",
            "baseName": "LT",
            "type": "Array<CertificationsTvList200ResponseCertificationsLTInner>"
        },
        {
            "name": "NL",
            "baseName": "NL",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "PH",
            "baseName": "PH",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "PT",
            "baseName": "PT",
            "type": "Array<CertificationsTvList200ResponseCertificationsPTInner>"
        },
        {
            "name": "RU",
            "baseName": "RU",
            "type": "Array<CertificationsTvList200ResponseCertificationsRUInner>"
        },
        {
            "name": "SK",
            "baseName": "SK",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "TH",
            "baseName": "TH",
            "type": "Array<CertificationsTvList200ResponseCertificationsTHInner>"
        },
        {
            "name": "US",
            "baseName": "US",
            "type": "Array<CertificationsTvList200ResponseCertificationsUSInner>"
        },
        {
            "name": "IT",
            "baseName": "IT",
            "type": "Array<CertificationsTvList200ResponseCertificationsITInner>"
        },
        {
            "name": "FI",
            "baseName": "FI",
            "type": "Array<CertificationsTvList200ResponseCertificationsFIInner>"
        },
        {
            "name": "MY",
            "baseName": "MY",
            "type": "Array<CertificationsTvList200ResponseCertificationsMYInner>"
        },
        {
            "name": "NZ",
            "baseName": "NZ",
            "type": "Array<CertificationsTvList200ResponseCertificationsNZInner>"
        },
        {
            "name": "NO",
            "baseName": "NO",
            "type": "Array<CertificationsTvList200ResponseCertificationsNOInner>"
        },
        {
            "name": "BG",
            "baseName": "BG",
            "type": "Array<CertificationsTvList200ResponseCertificationsBGInner>"
        },
        {
            "name": "MX",
            "baseName": "MX",
            "type": "Array<CertificationsTvList200ResponseCertificationsMXInner>"
        },
        {
            "name": "IN",
            "baseName": "IN",
            "type": "Array<CertificationsTvList200ResponseCertificationsINInner>"
        },
        {
            "name": "DK",
            "baseName": "DK",
            "type": "Array<CertificationsTvList200ResponseCertificationsDKInner>"
        },
        {
            "name": "SE",
            "baseName": "SE",
            "type": "Array<CertificationsTvList200ResponseCertificationsSEInner>"
        },
        {
            "name": "ID",
            "baseName": "ID",
            "type": "Array<CertificationsTvList200ResponseCertificationsIDInner>"
        },
        {
            "name": "TR",
            "baseName": "TR",
            "type": "Array<CertificationsTvList200ResponseCertificationsTRInner>"
        },
        {
            "name": "AR",
            "baseName": "AR",
            "type": "Array<CertificationsTvList200ResponseCertificationsARInner>"
        },
        {
            "name": "PL",
            "baseName": "PL",
            "type": "Array<CertificationsTvList200ResponseCertificationsPLInner>"
        },
        {
            "name": "MA",
            "baseName": "MA",
            "type": "Array<CertificationsTvList200ResponseCertificationsMAInner>"
        },
        {
            "name": "GR",
            "baseName": "GR",
            "type": "Array<CertificationsTvList200ResponseCertificationsGRInner>"
        },
        {
            "name": "IL",
            "baseName": "IL",
            "type": "Array<CertificationsTvList200ResponseCertificationsILInner>"
        },
        {
            "name": "TW",
            "baseName": "TW",
            "type": "Array<CertificationsTvList200ResponseCertificationsTWInner>"
        },
        {
            "name": "ZA",
            "baseName": "ZA",
            "type": "Array<CertificationsTvList200ResponseCertificationsZAInner>"
        },
        {
            "name": "SG",
            "baseName": "SG",
            "type": "Array<CertificationMovieList200ResponseCertificationsPRInner>"
        },
        {
            "name": "PR",
            "baseName": "PR",
            "type": "Array<CertificationsTvList200ResponseCertificationsPRInner>"
        },
        {
            "name": "VI",
            "baseName": "VI",
            "type": "Array<CertificationsTvList200ResponseCertificationsPRInner>"
        }    ];

    static getAttributeTypeMap() {
        return CertificationsTvList200ResponseCertifications.attributeTypeMap;
    }
}

