/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CertificationMovieList200ResponseCertificationsARInner } from './certificationMovieList200ResponseCertificationsARInner';
import { CertificationMovieList200ResponseCertificationsAUInner } from './certificationMovieList200ResponseCertificationsAUInner';
import { CertificationMovieList200ResponseCertificationsBGInner } from './certificationMovieList200ResponseCertificationsBGInner';
import { CertificationMovieList200ResponseCertificationsBRInner } from './certificationMovieList200ResponseCertificationsBRInner';
import { CertificationMovieList200ResponseCertificationsCAInner } from './certificationMovieList200ResponseCertificationsCAInner';
import { CertificationMovieList200ResponseCertificationsCAQCInner } from './certificationMovieList200ResponseCertificationsCAQCInner';
import { CertificationMovieList200ResponseCertificationsCHInner } from './certificationMovieList200ResponseCertificationsCHInner';
import { CertificationMovieList200ResponseCertificationsDEInner } from './certificationMovieList200ResponseCertificationsDEInner';
import { CertificationMovieList200ResponseCertificationsESInner } from './certificationMovieList200ResponseCertificationsESInner';
import { CertificationMovieList200ResponseCertificationsFIInner } from './certificationMovieList200ResponseCertificationsFIInner';
import { CertificationMovieList200ResponseCertificationsFRInner } from './certificationMovieList200ResponseCertificationsFRInner';
import { CertificationMovieList200ResponseCertificationsGBInner } from './certificationMovieList200ResponseCertificationsGBInner';
import { CertificationMovieList200ResponseCertificationsGRInner } from './certificationMovieList200ResponseCertificationsGRInner';
import { CertificationMovieList200ResponseCertificationsHKInner } from './certificationMovieList200ResponseCertificationsHKInner';
import { CertificationMovieList200ResponseCertificationsHUInner } from './certificationMovieList200ResponseCertificationsHUInner';
import { CertificationMovieList200ResponseCertificationsIDInner } from './certificationMovieList200ResponseCertificationsIDInner';
import { CertificationMovieList200ResponseCertificationsIEInner } from './certificationMovieList200ResponseCertificationsIEInner';
import { CertificationMovieList200ResponseCertificationsILInner } from './certificationMovieList200ResponseCertificationsILInner';
import { CertificationMovieList200ResponseCertificationsINInner } from './certificationMovieList200ResponseCertificationsINInner';
import { CertificationMovieList200ResponseCertificationsJPInner } from './certificationMovieList200ResponseCertificationsJPInner';
import { CertificationMovieList200ResponseCertificationsKRInner } from './certificationMovieList200ResponseCertificationsKRInner';
import { CertificationMovieList200ResponseCertificationsLUInner } from './certificationMovieList200ResponseCertificationsLUInner';
import { CertificationMovieList200ResponseCertificationsLVInner } from './certificationMovieList200ResponseCertificationsLVInner';
import { CertificationMovieList200ResponseCertificationsMOInner } from './certificationMovieList200ResponseCertificationsMOInner';
import { CertificationMovieList200ResponseCertificationsMXInner } from './certificationMovieList200ResponseCertificationsMXInner';
import { CertificationMovieList200ResponseCertificationsNLInner } from './certificationMovieList200ResponseCertificationsNLInner';
import { CertificationMovieList200ResponseCertificationsNOInner } from './certificationMovieList200ResponseCertificationsNOInner';
import { CertificationMovieList200ResponseCertificationsNZInner } from './certificationMovieList200ResponseCertificationsNZInner';
import { CertificationMovieList200ResponseCertificationsPRInner } from './certificationMovieList200ResponseCertificationsPRInner';
import { CertificationMovieList200ResponseCertificationsPTInner } from './certificationMovieList200ResponseCertificationsPTInner';
import { CertificationMovieList200ResponseCertificationsRUInner } from './certificationMovieList200ResponseCertificationsRUInner';
import { CertificationMovieList200ResponseCertificationsSEInner } from './certificationMovieList200ResponseCertificationsSEInner';
import { CertificationMovieList200ResponseCertificationsSGInner } from './certificationMovieList200ResponseCertificationsSGInner';
import { CertificationMovieList200ResponseCertificationsSKInner } from './certificationMovieList200ResponseCertificationsSKInner';
import { CertificationMovieList200ResponseCertificationsTHInner } from './certificationMovieList200ResponseCertificationsTHInner';
import { CertificationMovieList200ResponseCertificationsTRInner } from './certificationMovieList200ResponseCertificationsTRInner';
import { CertificationMovieList200ResponseCertificationsTWInner } from './certificationMovieList200ResponseCertificationsTWInner';
import { CertificationMovieList200ResponseCertificationsUSInner } from './certificationMovieList200ResponseCertificationsUSInner';
import { CertificationMovieList200ResponseCertificationsVIInner } from './certificationMovieList200ResponseCertificationsVIInner';
import { CertificationMovieList200ResponseCertificationsZAInner } from './certificationMovieList200ResponseCertificationsZAInner';

export class CertificationMovieList200ResponseCertifications {
    'AU'?: Array<CertificationMovieList200ResponseCertificationsAUInner>;
    'BG'?: Array<CertificationMovieList200ResponseCertificationsBGInner>;
    'BR'?: Array<CertificationMovieList200ResponseCertificationsBRInner>;
    'CA'?: Array<CertificationMovieList200ResponseCertificationsCAInner>;
    'CA_QC'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'DE'?: Array<CertificationMovieList200ResponseCertificationsDEInner>;
    'DK'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'ES'?: Array<CertificationMovieList200ResponseCertificationsESInner>;
    'FI'?: Array<CertificationMovieList200ResponseCertificationsFIInner>;
    'FR'?: Array<CertificationMovieList200ResponseCertificationsFRInner>;
    'GB'?: Array<CertificationMovieList200ResponseCertificationsGBInner>;
    'HU'?: Array<CertificationMovieList200ResponseCertificationsHUInner>;
    'IN'?: Array<CertificationMovieList200ResponseCertificationsINInner>;
    'IT'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'LT'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'MY'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'NL'?: Array<CertificationMovieList200ResponseCertificationsNLInner>;
    'NO'?: Array<CertificationMovieList200ResponseCertificationsNOInner>;
    'NZ'?: Array<CertificationMovieList200ResponseCertificationsNZInner>;
    'PH'?: Array<CertificationMovieList200ResponseCertificationsCAQCInner>;
    'PT'?: Array<CertificationMovieList200ResponseCertificationsPTInner>;
    'RU'?: Array<CertificationMovieList200ResponseCertificationsRUInner>;
    'SE'?: Array<CertificationMovieList200ResponseCertificationsSEInner>;
    'US'?: Array<CertificationMovieList200ResponseCertificationsUSInner>;
    'KR'?: Array<CertificationMovieList200ResponseCertificationsKRInner>;
    'SK'?: Array<CertificationMovieList200ResponseCertificationsSKInner>;
    'TH'?: Array<CertificationMovieList200ResponseCertificationsTHInner>;
    'MX'?: Array<CertificationMovieList200ResponseCertificationsMXInner>;
    'ID'?: Array<CertificationMovieList200ResponseCertificationsIDInner>;
    'TR'?: Array<CertificationMovieList200ResponseCertificationsTRInner>;
    'AR'?: Array<CertificationMovieList200ResponseCertificationsARInner>;
    'GR'?: Array<CertificationMovieList200ResponseCertificationsGRInner>;
    'TW'?: Array<CertificationMovieList200ResponseCertificationsTWInner>;
    'ZA'?: Array<CertificationMovieList200ResponseCertificationsZAInner>;
    'SG'?: Array<CertificationMovieList200ResponseCertificationsSGInner>;
    'IE'?: Array<CertificationMovieList200ResponseCertificationsIEInner>;
    'PR'?: Array<CertificationMovieList200ResponseCertificationsPRInner>;
    'JP'?: Array<CertificationMovieList200ResponseCertificationsJPInner>;
    'VI'?: Array<CertificationMovieList200ResponseCertificationsVIInner>;
    'CH'?: Array<CertificationMovieList200ResponseCertificationsCHInner>;
    'IL'?: Array<CertificationMovieList200ResponseCertificationsILInner>;
    'HK'?: Array<CertificationMovieList200ResponseCertificationsHKInner>;
    'MO'?: Array<CertificationMovieList200ResponseCertificationsMOInner>;
    'LV'?: Array<CertificationMovieList200ResponseCertificationsLVInner>;
    'LU'?: Array<CertificationMovieList200ResponseCertificationsLUInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "AU",
            "baseName": "AU",
            "type": "Array<CertificationMovieList200ResponseCertificationsAUInner>"
        },
        {
            "name": "BG",
            "baseName": "BG",
            "type": "Array<CertificationMovieList200ResponseCertificationsBGInner>"
        },
        {
            "name": "BR",
            "baseName": "BR",
            "type": "Array<CertificationMovieList200ResponseCertificationsBRInner>"
        },
        {
            "name": "CA",
            "baseName": "CA",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAInner>"
        },
        {
            "name": "CA_QC",
            "baseName": "CA-QC",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "DE",
            "baseName": "DE",
            "type": "Array<CertificationMovieList200ResponseCertificationsDEInner>"
        },
        {
            "name": "DK",
            "baseName": "DK",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "ES",
            "baseName": "ES",
            "type": "Array<CertificationMovieList200ResponseCertificationsESInner>"
        },
        {
            "name": "FI",
            "baseName": "FI",
            "type": "Array<CertificationMovieList200ResponseCertificationsFIInner>"
        },
        {
            "name": "FR",
            "baseName": "FR",
            "type": "Array<CertificationMovieList200ResponseCertificationsFRInner>"
        },
        {
            "name": "GB",
            "baseName": "GB",
            "type": "Array<CertificationMovieList200ResponseCertificationsGBInner>"
        },
        {
            "name": "HU",
            "baseName": "HU",
            "type": "Array<CertificationMovieList200ResponseCertificationsHUInner>"
        },
        {
            "name": "IN",
            "baseName": "IN",
            "type": "Array<CertificationMovieList200ResponseCertificationsINInner>"
        },
        {
            "name": "IT",
            "baseName": "IT",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "LT",
            "baseName": "LT",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "MY",
            "baseName": "MY",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "NL",
            "baseName": "NL",
            "type": "Array<CertificationMovieList200ResponseCertificationsNLInner>"
        },
        {
            "name": "NO",
            "baseName": "NO",
            "type": "Array<CertificationMovieList200ResponseCertificationsNOInner>"
        },
        {
            "name": "NZ",
            "baseName": "NZ",
            "type": "Array<CertificationMovieList200ResponseCertificationsNZInner>"
        },
        {
            "name": "PH",
            "baseName": "PH",
            "type": "Array<CertificationMovieList200ResponseCertificationsCAQCInner>"
        },
        {
            "name": "PT",
            "baseName": "PT",
            "type": "Array<CertificationMovieList200ResponseCertificationsPTInner>"
        },
        {
            "name": "RU",
            "baseName": "RU",
            "type": "Array<CertificationMovieList200ResponseCertificationsRUInner>"
        },
        {
            "name": "SE",
            "baseName": "SE",
            "type": "Array<CertificationMovieList200ResponseCertificationsSEInner>"
        },
        {
            "name": "US",
            "baseName": "US",
            "type": "Array<CertificationMovieList200ResponseCertificationsUSInner>"
        },
        {
            "name": "KR",
            "baseName": "KR",
            "type": "Array<CertificationMovieList200ResponseCertificationsKRInner>"
        },
        {
            "name": "SK",
            "baseName": "SK",
            "type": "Array<CertificationMovieList200ResponseCertificationsSKInner>"
        },
        {
            "name": "TH",
            "baseName": "TH",
            "type": "Array<CertificationMovieList200ResponseCertificationsTHInner>"
        },
        {
            "name": "MX",
            "baseName": "MX",
            "type": "Array<CertificationMovieList200ResponseCertificationsMXInner>"
        },
        {
            "name": "ID",
            "baseName": "ID",
            "type": "Array<CertificationMovieList200ResponseCertificationsIDInner>"
        },
        {
            "name": "TR",
            "baseName": "TR",
            "type": "Array<CertificationMovieList200ResponseCertificationsTRInner>"
        },
        {
            "name": "AR",
            "baseName": "AR",
            "type": "Array<CertificationMovieList200ResponseCertificationsARInner>"
        },
        {
            "name": "GR",
            "baseName": "GR",
            "type": "Array<CertificationMovieList200ResponseCertificationsGRInner>"
        },
        {
            "name": "TW",
            "baseName": "TW",
            "type": "Array<CertificationMovieList200ResponseCertificationsTWInner>"
        },
        {
            "name": "ZA",
            "baseName": "ZA",
            "type": "Array<CertificationMovieList200ResponseCertificationsZAInner>"
        },
        {
            "name": "SG",
            "baseName": "SG",
            "type": "Array<CertificationMovieList200ResponseCertificationsSGInner>"
        },
        {
            "name": "IE",
            "baseName": "IE",
            "type": "Array<CertificationMovieList200ResponseCertificationsIEInner>"
        },
        {
            "name": "PR",
            "baseName": "PR",
            "type": "Array<CertificationMovieList200ResponseCertificationsPRInner>"
        },
        {
            "name": "JP",
            "baseName": "JP",
            "type": "Array<CertificationMovieList200ResponseCertificationsJPInner>"
        },
        {
            "name": "VI",
            "baseName": "VI",
            "type": "Array<CertificationMovieList200ResponseCertificationsVIInner>"
        },
        {
            "name": "CH",
            "baseName": "CH",
            "type": "Array<CertificationMovieList200ResponseCertificationsCHInner>"
        },
        {
            "name": "IL",
            "baseName": "IL",
            "type": "Array<CertificationMovieList200ResponseCertificationsILInner>"
        },
        {
            "name": "HK",
            "baseName": "HK",
            "type": "Array<CertificationMovieList200ResponseCertificationsHKInner>"
        },
        {
            "name": "MO",
            "baseName": "MO",
            "type": "Array<CertificationMovieList200ResponseCertificationsMOInner>"
        },
        {
            "name": "LV",
            "baseName": "LV",
            "type": "Array<CertificationMovieList200ResponseCertificationsLVInner>"
        },
        {
            "name": "LU",
            "baseName": "LU",
            "type": "Array<CertificationMovieList200ResponseCertificationsLUInner>"
        }    ];

    static getAttributeTypeMap() {
        return CertificationMovieList200ResponseCertifications.attributeTypeMap;
    }
}

