/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CollectionDetails200ResponsePartsInner } from './collectionDetails200ResponsePartsInner';

export class CollectionDetails200Response {
    'id'?: number = 0;
    'name'?: string;
    'overview'?: string;
    'poster_path'?: string;
    'backdrop_path'?: string;
    'parts'?: Array<CollectionDetails200ResponsePartsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "overview",
            "baseName": "overview",
            "type": "string"
        },
        {
            "name": "poster_path",
            "baseName": "poster_path",
            "type": "string"
        },
        {
            "name": "backdrop_path",
            "baseName": "backdrop_path",
            "type": "string"
        },
        {
            "name": "parts",
            "baseName": "parts",
            "type": "Array<CollectionDetails200ResponsePartsInner>"
        }    ];

    static getAttributeTypeMap() {
        return CollectionDetails200Response.attributeTypeMap;
    }
}

