/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CollectionImages200ResponseBackdropsInner } from './collectionImages200ResponseBackdropsInner';
import { CollectionImages200ResponsePostersInner } from './collectionImages200ResponsePostersInner';

export class CollectionImages200Response {
    'id'?: number = 0;
    'backdrops'?: Array<CollectionImages200ResponseBackdropsInner>;
    'posters'?: Array<CollectionImages200ResponsePostersInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "backdrops",
            "baseName": "backdrops",
            "type": "Array<CollectionImages200ResponseBackdropsInner>"
        },
        {
            "name": "posters",
            "baseName": "posters",
            "type": "Array<CollectionImages200ResponsePostersInner>"
        }    ];

    static getAttributeTypeMap() {
        return CollectionImages200Response.attributeTypeMap;
    }
}

