/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ConfigurationJobs200ResponseInner {
    'department'?: string;
    'jobs'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "department",
            "baseName": "department",
            "type": "string"
        },
        {
            "name": "jobs",
            "baseName": "jobs",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ConfigurationJobs200ResponseInner.attributeTypeMap;
    }
}

