/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ConfigurationDetails200ResponseImages {
    'base_url'?: string;
    'secure_base_url'?: string;
    'backdrop_sizes'?: Array<string>;
    'logo_sizes'?: Array<string>;
    'poster_sizes'?: Array<string>;
    'profile_sizes'?: Array<string>;
    'still_sizes'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "base_url",
            "baseName": "base_url",
            "type": "string"
        },
        {
            "name": "secure_base_url",
            "baseName": "secure_base_url",
            "type": "string"
        },
        {
            "name": "backdrop_sizes",
            "baseName": "backdrop_sizes",
            "type": "Array<string>"
        },
        {
            "name": "logo_sizes",
            "baseName": "logo_sizes",
            "type": "Array<string>"
        },
        {
            "name": "poster_sizes",
            "baseName": "poster_sizes",
            "type": "Array<string>"
        },
        {
            "name": "profile_sizes",
            "baseName": "profile_sizes",
            "type": "Array<string>"
        },
        {
            "name": "still_sizes",
            "baseName": "still_sizes",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ConfigurationDetails200ResponseImages.attributeTypeMap;
    }
}

