/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreditDetails200ResponseMedia } from './creditDetails200ResponseMedia';
import { CreditDetails200ResponsePerson } from './creditDetails200ResponsePerson';

export class CreditDetails200Response {
    'credit_type'?: string;
    'department'?: string;
    'job'?: string;
    'media'?: CreditDetails200ResponseMedia;
    'media_type'?: string;
    'id'?: string;
    'person'?: CreditDetails200ResponsePerson;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "credit_type",
            "baseName": "credit_type",
            "type": "string"
        },
        {
            "name": "department",
            "baseName": "department",
            "type": "string"
        },
        {
            "name": "job",
            "baseName": "job",
            "type": "string"
        },
        {
            "name": "media",
            "baseName": "media",
            "type": "CreditDetails200ResponseMedia"
        },
        {
            "name": "media_type",
            "baseName": "media_type",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "person",
            "baseName": "person",
            "type": "CreditDetails200ResponsePerson"
        }    ];

    static getAttributeTypeMap() {
        return CreditDetails200Response.attributeTypeMap;
    }
}

