/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GenreMovieList200ResponseGenresInner } from './genreMovieList200ResponseGenresInner';

export class GenreMovieList200Response {
    'genres'?: Array<GenreMovieList200ResponseGenresInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "genres",
            "baseName": "genres",
            "type": "Array<GenreMovieList200ResponseGenresInner>"
        }    ];

    static getAttributeTypeMap() {
        return GenreMovieList200Response.attributeTypeMap;
    }
}

