/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ListDetails200ResponseItemsInner } from './listDetails200ResponseItemsInner';

export class ListDetails200Response {
    'created_by'?: string;
    'description'?: string;
    'favorite_count'?: number = 0;
    'id'?: string;
    'items'?: Array<ListDetails200ResponseItemsInner>;
    'item_count'?: number = 0;
    'iso_639_1'?: string;
    'name'?: string;
    'poster_path'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "created_by",
            "baseName": "created_by",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "favorite_count",
            "baseName": "favorite_count",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<ListDetails200ResponseItemsInner>"
        },
        {
            "name": "item_count",
            "baseName": "item_count",
            "type": "number"
        },
        {
            "name": "iso_639_1",
            "baseName": "iso_639_1",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "poster_path",
            "baseName": "poster_path",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ListDetails200Response.attributeTypeMap;
    }
}

