/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieReviews200ResponseResultsInnerAuthorDetails } from './movieReviews200ResponseResultsInnerAuthorDetails';

export class MovieReviews200ResponseResultsInner {
    'author'?: string;
    'author_details'?: MovieReviews200ResponseResultsInnerAuthorDetails;
    'content'?: string;
    'created_at'?: string;
    'id'?: string;
    'updated_at'?: string;
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "author",
            "baseName": "author",
            "type": "string"
        },
        {
            "name": "author_details",
            "baseName": "author_details",
            "type": "MovieReviews200ResponseResultsInnerAuthorDetails"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MovieReviews200ResponseResultsInner.attributeTypeMap;
    }
}

