/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieKeywords200ResponseKeywordsInner } from './movieKeywords200ResponseKeywordsInner';

export class MovieKeywords200Response {
    'id'?: number = 0;
    'keywords'?: Array<MovieKeywords200ResponseKeywordsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "keywords",
            "baseName": "keywords",
            "type": "Array<MovieKeywords200ResponseKeywordsInner>"
        }    ];

    static getAttributeTypeMap() {
        return MovieKeywords200Response.attributeTypeMap;
    }
}

