/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieAlternativeTitles200ResponseTitlesInner } from './movieAlternativeTitles200ResponseTitlesInner';

export class MovieAlternativeTitles200Response {
    'id'?: number = 0;
    'titles'?: Array<MovieAlternativeTitles200ResponseTitlesInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "titles",
            "baseName": "titles",
            "type": "Array<MovieAlternativeTitles200ResponseTitlesInner>"
        }    ];

    static getAttributeTypeMap() {
        return MovieAlternativeTitles200Response.attributeTypeMap;
    }
}

