/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MovieExternalIds200Response {
    'id'?: number = 0;
    'imdb_id'?: string;
    'wikidata_id'?: any | null;
    'facebook_id'?: string;
    'instagram_id'?: any | null;
    'twitter_id'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "imdb_id",
            "baseName": "imdb_id",
            "type": "string"
        },
        {
            "name": "wikidata_id",
            "baseName": "wikidata_id",
            "type": "any"
        },
        {
            "name": "facebook_id",
            "baseName": "facebook_id",
            "type": "string"
        },
        {
            "name": "instagram_id",
            "baseName": "instagram_id",
            "type": "any"
        },
        {
            "name": "twitter_id",
            "baseName": "twitter_id",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return MovieExternalIds200Response.attributeTypeMap;
    }
}

