/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieReleaseDates200ResponseResultsInnerReleaseDatesInner } from './movieReleaseDates200ResponseResultsInnerReleaseDatesInner';

export class MovieReleaseDates200ResponseResultsInner {
    'iso_3166_1'?: string;
    'release_dates'?: Array<MovieReleaseDates200ResponseResultsInnerReleaseDatesInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "iso_3166_1",
            "baseName": "iso_3166_1",
            "type": "string"
        },
        {
            "name": "release_dates",
            "baseName": "release_dates",
            "type": "Array<MovieReleaseDates200ResponseResultsInnerReleaseDatesInner>"
        }    ];

    static getAttributeTypeMap() {
        return MovieReleaseDates200ResponseResultsInner.attributeTypeMap;
    }
}

