/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieWatchProviders200ResponseResultsALBuyInner } from './movieWatchProviders200ResponseResultsALBuyInner';
import { MovieWatchProviders200ResponseResultsMKFlatrateInner } from './movieWatchProviders200ResponseResultsMKFlatrateInner';

export class MovieWatchProviders200ResponseResultsMK {
    'link'?: string;
    'flatrate'?: Array<MovieWatchProviders200ResponseResultsMKFlatrateInner>;
    'buy'?: Array<MovieWatchProviders200ResponseResultsALBuyInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<MovieWatchProviders200ResponseResultsMKFlatrateInner>"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<MovieWatchProviders200ResponseResultsALBuyInner>"
        }    ];

    static getAttributeTypeMap() {
        return MovieWatchProviders200ResponseResultsMK.attributeTypeMap;
    }
}

