/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MovieLists200ResponseResultsInner {
    'description'?: string;
    'favorite_count'?: number = 0;
    'id'?: number = 0;
    'item_count'?: number = 0;
    'iso_639_1'?: string;
    'list_type'?: string;
    'name'?: string;
    'poster_path'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "favorite_count",
            "baseName": "favorite_count",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "item_count",
            "baseName": "item_count",
            "type": "number"
        },
        {
            "name": "iso_639_1",
            "baseName": "iso_639_1",
            "type": "string"
        },
        {
            "name": "list_type",
            "baseName": "list_type",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "poster_path",
            "baseName": "poster_path",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return MovieLists200ResponseResultsInner.attributeTypeMap;
    }
}

