/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieCredits200ResponseCastInner } from './movieCredits200ResponseCastInner';
import { MovieCredits200ResponseCrewInner } from './movieCredits200ResponseCrewInner';

export class MovieCredits200Response {
    'id'?: number = 0;
    'cast'?: Array<MovieCredits200ResponseCastInner>;
    'crew'?: Array<MovieCredits200ResponseCrewInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "cast",
            "baseName": "cast",
            "type": "Array<MovieCredits200ResponseCastInner>"
        },
        {
            "name": "crew",
            "baseName": "crew",
            "type": "Array<MovieCredits200ResponseCrewInner>"
        }    ];

    static getAttributeTypeMap() {
        return MovieCredits200Response.attributeTypeMap;
    }
}

