/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MovieUpcomingList200ResponseDates {
    'maximum'?: string;
    'minimum'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "maximum",
            "baseName": "maximum",
            "type": "string"
        },
        {
            "name": "minimum",
            "baseName": "minimum",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MovieUpcomingList200ResponseDates.attributeTypeMap;
    }
}

