/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieWatchProviders200ResponseResultsAE } from './movieWatchProviders200ResponseResultsAE';
import { MovieWatchProviders200ResponseResultsAL } from './movieWatchProviders200ResponseResultsAL';
import { MovieWatchProviders200ResponseResultsAR } from './movieWatchProviders200ResponseResultsAR';
import { MovieWatchProviders200ResponseResultsAT } from './movieWatchProviders200ResponseResultsAT';
import { MovieWatchProviders200ResponseResultsAU } from './movieWatchProviders200ResponseResultsAU';
import { MovieWatchProviders200ResponseResultsBA } from './movieWatchProviders200ResponseResultsBA';
import { MovieWatchProviders200ResponseResultsBB } from './movieWatchProviders200ResponseResultsBB';
import { MovieWatchProviders200ResponseResultsBE } from './movieWatchProviders200ResponseResultsBE';
import { MovieWatchProviders200ResponseResultsBG } from './movieWatchProviders200ResponseResultsBG';
import { MovieWatchProviders200ResponseResultsBH } from './movieWatchProviders200ResponseResultsBH';
import { MovieWatchProviders200ResponseResultsBO } from './movieWatchProviders200ResponseResultsBO';
import { MovieWatchProviders200ResponseResultsBR } from './movieWatchProviders200ResponseResultsBR';
import { MovieWatchProviders200ResponseResultsBS } from './movieWatchProviders200ResponseResultsBS';
import { MovieWatchProviders200ResponseResultsCA } from './movieWatchProviders200ResponseResultsCA';
import { MovieWatchProviders200ResponseResultsCH } from './movieWatchProviders200ResponseResultsCH';
import { MovieWatchProviders200ResponseResultsCL } from './movieWatchProviders200ResponseResultsCL';
import { MovieWatchProviders200ResponseResultsCO } from './movieWatchProviders200ResponseResultsCO';
import { MovieWatchProviders200ResponseResultsCR } from './movieWatchProviders200ResponseResultsCR';
import { MovieWatchProviders200ResponseResultsCV } from './movieWatchProviders200ResponseResultsCV';
import { MovieWatchProviders200ResponseResultsCZ } from './movieWatchProviders200ResponseResultsCZ';
import { MovieWatchProviders200ResponseResultsDE } from './movieWatchProviders200ResponseResultsDE';
import { MovieWatchProviders200ResponseResultsDK } from './movieWatchProviders200ResponseResultsDK';
import { MovieWatchProviders200ResponseResultsDO } from './movieWatchProviders200ResponseResultsDO';
import { MovieWatchProviders200ResponseResultsEC } from './movieWatchProviders200ResponseResultsEC';
import { MovieWatchProviders200ResponseResultsEE } from './movieWatchProviders200ResponseResultsEE';
import { MovieWatchProviders200ResponseResultsEG } from './movieWatchProviders200ResponseResultsEG';
import { MovieWatchProviders200ResponseResultsES } from './movieWatchProviders200ResponseResultsES';
import { MovieWatchProviders200ResponseResultsFI } from './movieWatchProviders200ResponseResultsFI';
import { MovieWatchProviders200ResponseResultsFJ } from './movieWatchProviders200ResponseResultsFJ';
import { MovieWatchProviders200ResponseResultsFR } from './movieWatchProviders200ResponseResultsFR';
import { MovieWatchProviders200ResponseResultsGB } from './movieWatchProviders200ResponseResultsGB';
import { MovieWatchProviders200ResponseResultsGF } from './movieWatchProviders200ResponseResultsGF';
import { MovieWatchProviders200ResponseResultsGI } from './movieWatchProviders200ResponseResultsGI';
import { MovieWatchProviders200ResponseResultsGR } from './movieWatchProviders200ResponseResultsGR';
import { MovieWatchProviders200ResponseResultsGT } from './movieWatchProviders200ResponseResultsGT';
import { MovieWatchProviders200ResponseResultsHK } from './movieWatchProviders200ResponseResultsHK';
import { MovieWatchProviders200ResponseResultsHN } from './movieWatchProviders200ResponseResultsHN';
import { MovieWatchProviders200ResponseResultsHR } from './movieWatchProviders200ResponseResultsHR';
import { MovieWatchProviders200ResponseResultsHU } from './movieWatchProviders200ResponseResultsHU';
import { MovieWatchProviders200ResponseResultsID } from './movieWatchProviders200ResponseResultsID';
import { MovieWatchProviders200ResponseResultsIE } from './movieWatchProviders200ResponseResultsIE';
import { MovieWatchProviders200ResponseResultsIL } from './movieWatchProviders200ResponseResultsIL';
import { MovieWatchProviders200ResponseResultsIN } from './movieWatchProviders200ResponseResultsIN';
import { MovieWatchProviders200ResponseResultsIQ } from './movieWatchProviders200ResponseResultsIQ';
import { MovieWatchProviders200ResponseResultsIS } from './movieWatchProviders200ResponseResultsIS';
import { MovieWatchProviders200ResponseResultsIT } from './movieWatchProviders200ResponseResultsIT';
import { MovieWatchProviders200ResponseResultsJM } from './movieWatchProviders200ResponseResultsJM';
import { MovieWatchProviders200ResponseResultsJO } from './movieWatchProviders200ResponseResultsJO';
import { MovieWatchProviders200ResponseResultsJP } from './movieWatchProviders200ResponseResultsJP';
import { MovieWatchProviders200ResponseResultsKR } from './movieWatchProviders200ResponseResultsKR';
import { MovieWatchProviders200ResponseResultsKW } from './movieWatchProviders200ResponseResultsKW';
import { MovieWatchProviders200ResponseResultsLB } from './movieWatchProviders200ResponseResultsLB';
import { MovieWatchProviders200ResponseResultsLI } from './movieWatchProviders200ResponseResultsLI';
import { MovieWatchProviders200ResponseResultsLT } from './movieWatchProviders200ResponseResultsLT';
import { MovieWatchProviders200ResponseResultsLV } from './movieWatchProviders200ResponseResultsLV';
import { MovieWatchProviders200ResponseResultsMD } from './movieWatchProviders200ResponseResultsMD';
import { MovieWatchProviders200ResponseResultsMK } from './movieWatchProviders200ResponseResultsMK';
import { MovieWatchProviders200ResponseResultsMT } from './movieWatchProviders200ResponseResultsMT';
import { MovieWatchProviders200ResponseResultsMU } from './movieWatchProviders200ResponseResultsMU';
import { MovieWatchProviders200ResponseResultsMX } from './movieWatchProviders200ResponseResultsMX';
import { MovieWatchProviders200ResponseResultsMY } from './movieWatchProviders200ResponseResultsMY';
import { MovieWatchProviders200ResponseResultsMZ } from './movieWatchProviders200ResponseResultsMZ';
import { MovieWatchProviders200ResponseResultsNL } from './movieWatchProviders200ResponseResultsNL';
import { MovieWatchProviders200ResponseResultsNO } from './movieWatchProviders200ResponseResultsNO';
import { MovieWatchProviders200ResponseResultsNZ } from './movieWatchProviders200ResponseResultsNZ';
import { MovieWatchProviders200ResponseResultsOM } from './movieWatchProviders200ResponseResultsOM';
import { MovieWatchProviders200ResponseResultsPA } from './movieWatchProviders200ResponseResultsPA';
import { MovieWatchProviders200ResponseResultsPE } from './movieWatchProviders200ResponseResultsPE';
import { MovieWatchProviders200ResponseResultsPH } from './movieWatchProviders200ResponseResultsPH';
import { MovieWatchProviders200ResponseResultsPK } from './movieWatchProviders200ResponseResultsPK';
import { MovieWatchProviders200ResponseResultsPL } from './movieWatchProviders200ResponseResultsPL';
import { MovieWatchProviders200ResponseResultsPS } from './movieWatchProviders200ResponseResultsPS';
import { MovieWatchProviders200ResponseResultsPT } from './movieWatchProviders200ResponseResultsPT';
import { MovieWatchProviders200ResponseResultsPY } from './movieWatchProviders200ResponseResultsPY';
import { MovieWatchProviders200ResponseResultsQA } from './movieWatchProviders200ResponseResultsQA';
import { MovieWatchProviders200ResponseResultsRO } from './movieWatchProviders200ResponseResultsRO';
import { MovieWatchProviders200ResponseResultsRS } from './movieWatchProviders200ResponseResultsRS';
import { MovieWatchProviders200ResponseResultsRU } from './movieWatchProviders200ResponseResultsRU';
import { MovieWatchProviders200ResponseResultsSA } from './movieWatchProviders200ResponseResultsSA';
import { MovieWatchProviders200ResponseResultsSE } from './movieWatchProviders200ResponseResultsSE';
import { MovieWatchProviders200ResponseResultsSG } from './movieWatchProviders200ResponseResultsSG';
import { MovieWatchProviders200ResponseResultsSI } from './movieWatchProviders200ResponseResultsSI';
import { MovieWatchProviders200ResponseResultsSK } from './movieWatchProviders200ResponseResultsSK';
import { MovieWatchProviders200ResponseResultsSM } from './movieWatchProviders200ResponseResultsSM';
import { MovieWatchProviders200ResponseResultsSV } from './movieWatchProviders200ResponseResultsSV';
import { MovieWatchProviders200ResponseResultsTH } from './movieWatchProviders200ResponseResultsTH';
import { MovieWatchProviders200ResponseResultsTR } from './movieWatchProviders200ResponseResultsTR';
import { MovieWatchProviders200ResponseResultsTT } from './movieWatchProviders200ResponseResultsTT';
import { MovieWatchProviders200ResponseResultsTW } from './movieWatchProviders200ResponseResultsTW';
import { MovieWatchProviders200ResponseResultsUG } from './movieWatchProviders200ResponseResultsUG';
import { MovieWatchProviders200ResponseResultsUS } from './movieWatchProviders200ResponseResultsUS';
import { MovieWatchProviders200ResponseResultsUY } from './movieWatchProviders200ResponseResultsUY';
import { MovieWatchProviders200ResponseResultsVE } from './movieWatchProviders200ResponseResultsVE';
import { MovieWatchProviders200ResponseResultsYE } from './movieWatchProviders200ResponseResultsYE';
import { MovieWatchProviders200ResponseResultsZA } from './movieWatchProviders200ResponseResultsZA';

export class MovieWatchProviders200ResponseResults {
    'AE'?: MovieWatchProviders200ResponseResultsAE;
    'AL'?: MovieWatchProviders200ResponseResultsAL;
    'AR'?: MovieWatchProviders200ResponseResultsAR;
    'AT'?: MovieWatchProviders200ResponseResultsAT;
    'AU'?: MovieWatchProviders200ResponseResultsAU;
    'BA'?: MovieWatchProviders200ResponseResultsBA;
    'BB'?: MovieWatchProviders200ResponseResultsBB;
    'BE'?: MovieWatchProviders200ResponseResultsBE;
    'BG'?: MovieWatchProviders200ResponseResultsBG;
    'BH'?: MovieWatchProviders200ResponseResultsBH;
    'BO'?: MovieWatchProviders200ResponseResultsBO;
    'BR'?: MovieWatchProviders200ResponseResultsBR;
    'BS'?: MovieWatchProviders200ResponseResultsBS;
    'CA'?: MovieWatchProviders200ResponseResultsCA;
    'CH'?: MovieWatchProviders200ResponseResultsCH;
    'CL'?: MovieWatchProviders200ResponseResultsCL;
    'CO'?: MovieWatchProviders200ResponseResultsCO;
    'CR'?: MovieWatchProviders200ResponseResultsCR;
    'CV'?: MovieWatchProviders200ResponseResultsCV;
    'CZ'?: MovieWatchProviders200ResponseResultsCZ;
    'DE'?: MovieWatchProviders200ResponseResultsDE;
    'DK'?: MovieWatchProviders200ResponseResultsDK;
    'DO'?: MovieWatchProviders200ResponseResultsDO;
    'EC'?: MovieWatchProviders200ResponseResultsEC;
    'EE'?: MovieWatchProviders200ResponseResultsEE;
    'EG'?: MovieWatchProviders200ResponseResultsEG;
    'ES'?: MovieWatchProviders200ResponseResultsES;
    'FI'?: MovieWatchProviders200ResponseResultsFI;
    'FJ'?: MovieWatchProviders200ResponseResultsFJ;
    'FR'?: MovieWatchProviders200ResponseResultsFR;
    'GB'?: MovieWatchProviders200ResponseResultsGB;
    'GF'?: MovieWatchProviders200ResponseResultsGF;
    'GI'?: MovieWatchProviders200ResponseResultsGI;
    'GR'?: MovieWatchProviders200ResponseResultsGR;
    'GT'?: MovieWatchProviders200ResponseResultsGT;
    'HK'?: MovieWatchProviders200ResponseResultsHK;
    'HN'?: MovieWatchProviders200ResponseResultsHN;
    'HR'?: MovieWatchProviders200ResponseResultsHR;
    'HU'?: MovieWatchProviders200ResponseResultsHU;
    'ID'?: MovieWatchProviders200ResponseResultsID;
    'IE'?: MovieWatchProviders200ResponseResultsIE;
    'IL'?: MovieWatchProviders200ResponseResultsIL;
    'IN'?: MovieWatchProviders200ResponseResultsIN;
    'IQ'?: MovieWatchProviders200ResponseResultsIQ;
    'IS'?: MovieWatchProviders200ResponseResultsIS;
    'IT'?: MovieWatchProviders200ResponseResultsIT;
    'JM'?: MovieWatchProviders200ResponseResultsJM;
    'JO'?: MovieWatchProviders200ResponseResultsJO;
    'JP'?: MovieWatchProviders200ResponseResultsJP;
    'KR'?: MovieWatchProviders200ResponseResultsKR;
    'KW'?: MovieWatchProviders200ResponseResultsKW;
    'LB'?: MovieWatchProviders200ResponseResultsLB;
    'LI'?: MovieWatchProviders200ResponseResultsLI;
    'LT'?: MovieWatchProviders200ResponseResultsLT;
    'LV'?: MovieWatchProviders200ResponseResultsLV;
    'MD'?: MovieWatchProviders200ResponseResultsMD;
    'MK'?: MovieWatchProviders200ResponseResultsMK;
    'MT'?: MovieWatchProviders200ResponseResultsMT;
    'MU'?: MovieWatchProviders200ResponseResultsMU;
    'MX'?: MovieWatchProviders200ResponseResultsMX;
    'MY'?: MovieWatchProviders200ResponseResultsMY;
    'MZ'?: MovieWatchProviders200ResponseResultsMZ;
    'NL'?: MovieWatchProviders200ResponseResultsNL;
    'NO'?: MovieWatchProviders200ResponseResultsNO;
    'NZ'?: MovieWatchProviders200ResponseResultsNZ;
    'OM'?: MovieWatchProviders200ResponseResultsOM;
    'PA'?: MovieWatchProviders200ResponseResultsPA;
    'PE'?: MovieWatchProviders200ResponseResultsPE;
    'PH'?: MovieWatchProviders200ResponseResultsPH;
    'PK'?: MovieWatchProviders200ResponseResultsPK;
    'PL'?: MovieWatchProviders200ResponseResultsPL;
    'PS'?: MovieWatchProviders200ResponseResultsPS;
    'PT'?: MovieWatchProviders200ResponseResultsPT;
    'PY'?: MovieWatchProviders200ResponseResultsPY;
    'QA'?: MovieWatchProviders200ResponseResultsQA;
    'RO'?: MovieWatchProviders200ResponseResultsRO;
    'RS'?: MovieWatchProviders200ResponseResultsRS;
    'RU'?: MovieWatchProviders200ResponseResultsRU;
    'SA'?: MovieWatchProviders200ResponseResultsSA;
    'SE'?: MovieWatchProviders200ResponseResultsSE;
    'SG'?: MovieWatchProviders200ResponseResultsSG;
    'SI'?: MovieWatchProviders200ResponseResultsSI;
    'SK'?: MovieWatchProviders200ResponseResultsSK;
    'SM'?: MovieWatchProviders200ResponseResultsSM;
    'SV'?: MovieWatchProviders200ResponseResultsSV;
    'TH'?: MovieWatchProviders200ResponseResultsTH;
    'TR'?: MovieWatchProviders200ResponseResultsTR;
    'TT'?: MovieWatchProviders200ResponseResultsTT;
    'TW'?: MovieWatchProviders200ResponseResultsTW;
    'UG'?: MovieWatchProviders200ResponseResultsUG;
    'US'?: MovieWatchProviders200ResponseResultsUS;
    'UY'?: MovieWatchProviders200ResponseResultsUY;
    'VE'?: MovieWatchProviders200ResponseResultsVE;
    'YE'?: MovieWatchProviders200ResponseResultsYE;
    'ZA'?: MovieWatchProviders200ResponseResultsZA;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "AE",
            "baseName": "AE",
            "type": "MovieWatchProviders200ResponseResultsAE"
        },
        {
            "name": "AL",
            "baseName": "AL",
            "type": "MovieWatchProviders200ResponseResultsAL"
        },
        {
            "name": "AR",
            "baseName": "AR",
            "type": "MovieWatchProviders200ResponseResultsAR"
        },
        {
            "name": "AT",
            "baseName": "AT",
            "type": "MovieWatchProviders200ResponseResultsAT"
        },
        {
            "name": "AU",
            "baseName": "AU",
            "type": "MovieWatchProviders200ResponseResultsAU"
        },
        {
            "name": "BA",
            "baseName": "BA",
            "type": "MovieWatchProviders200ResponseResultsBA"
        },
        {
            "name": "BB",
            "baseName": "BB",
            "type": "MovieWatchProviders200ResponseResultsBB"
        },
        {
            "name": "BE",
            "baseName": "BE",
            "type": "MovieWatchProviders200ResponseResultsBE"
        },
        {
            "name": "BG",
            "baseName": "BG",
            "type": "MovieWatchProviders200ResponseResultsBG"
        },
        {
            "name": "BH",
            "baseName": "BH",
            "type": "MovieWatchProviders200ResponseResultsBH"
        },
        {
            "name": "BO",
            "baseName": "BO",
            "type": "MovieWatchProviders200ResponseResultsBO"
        },
        {
            "name": "BR",
            "baseName": "BR",
            "type": "MovieWatchProviders200ResponseResultsBR"
        },
        {
            "name": "BS",
            "baseName": "BS",
            "type": "MovieWatchProviders200ResponseResultsBS"
        },
        {
            "name": "CA",
            "baseName": "CA",
            "type": "MovieWatchProviders200ResponseResultsCA"
        },
        {
            "name": "CH",
            "baseName": "CH",
            "type": "MovieWatchProviders200ResponseResultsCH"
        },
        {
            "name": "CL",
            "baseName": "CL",
            "type": "MovieWatchProviders200ResponseResultsCL"
        },
        {
            "name": "CO",
            "baseName": "CO",
            "type": "MovieWatchProviders200ResponseResultsCO"
        },
        {
            "name": "CR",
            "baseName": "CR",
            "type": "MovieWatchProviders200ResponseResultsCR"
        },
        {
            "name": "CV",
            "baseName": "CV",
            "type": "MovieWatchProviders200ResponseResultsCV"
        },
        {
            "name": "CZ",
            "baseName": "CZ",
            "type": "MovieWatchProviders200ResponseResultsCZ"
        },
        {
            "name": "DE",
            "baseName": "DE",
            "type": "MovieWatchProviders200ResponseResultsDE"
        },
        {
            "name": "DK",
            "baseName": "DK",
            "type": "MovieWatchProviders200ResponseResultsDK"
        },
        {
            "name": "DO",
            "baseName": "DO",
            "type": "MovieWatchProviders200ResponseResultsDO"
        },
        {
            "name": "EC",
            "baseName": "EC",
            "type": "MovieWatchProviders200ResponseResultsEC"
        },
        {
            "name": "EE",
            "baseName": "EE",
            "type": "MovieWatchProviders200ResponseResultsEE"
        },
        {
            "name": "EG",
            "baseName": "EG",
            "type": "MovieWatchProviders200ResponseResultsEG"
        },
        {
            "name": "ES",
            "baseName": "ES",
            "type": "MovieWatchProviders200ResponseResultsES"
        },
        {
            "name": "FI",
            "baseName": "FI",
            "type": "MovieWatchProviders200ResponseResultsFI"
        },
        {
            "name": "FJ",
            "baseName": "FJ",
            "type": "MovieWatchProviders200ResponseResultsFJ"
        },
        {
            "name": "FR",
            "baseName": "FR",
            "type": "MovieWatchProviders200ResponseResultsFR"
        },
        {
            "name": "GB",
            "baseName": "GB",
            "type": "MovieWatchProviders200ResponseResultsGB"
        },
        {
            "name": "GF",
            "baseName": "GF",
            "type": "MovieWatchProviders200ResponseResultsGF"
        },
        {
            "name": "GI",
            "baseName": "GI",
            "type": "MovieWatchProviders200ResponseResultsGI"
        },
        {
            "name": "GR",
            "baseName": "GR",
            "type": "MovieWatchProviders200ResponseResultsGR"
        },
        {
            "name": "GT",
            "baseName": "GT",
            "type": "MovieWatchProviders200ResponseResultsGT"
        },
        {
            "name": "HK",
            "baseName": "HK",
            "type": "MovieWatchProviders200ResponseResultsHK"
        },
        {
            "name": "HN",
            "baseName": "HN",
            "type": "MovieWatchProviders200ResponseResultsHN"
        },
        {
            "name": "HR",
            "baseName": "HR",
            "type": "MovieWatchProviders200ResponseResultsHR"
        },
        {
            "name": "HU",
            "baseName": "HU",
            "type": "MovieWatchProviders200ResponseResultsHU"
        },
        {
            "name": "ID",
            "baseName": "ID",
            "type": "MovieWatchProviders200ResponseResultsID"
        },
        {
            "name": "IE",
            "baseName": "IE",
            "type": "MovieWatchProviders200ResponseResultsIE"
        },
        {
            "name": "IL",
            "baseName": "IL",
            "type": "MovieWatchProviders200ResponseResultsIL"
        },
        {
            "name": "IN",
            "baseName": "IN",
            "type": "MovieWatchProviders200ResponseResultsIN"
        },
        {
            "name": "IQ",
            "baseName": "IQ",
            "type": "MovieWatchProviders200ResponseResultsIQ"
        },
        {
            "name": "IS",
            "baseName": "IS",
            "type": "MovieWatchProviders200ResponseResultsIS"
        },
        {
            "name": "IT",
            "baseName": "IT",
            "type": "MovieWatchProviders200ResponseResultsIT"
        },
        {
            "name": "JM",
            "baseName": "JM",
            "type": "MovieWatchProviders200ResponseResultsJM"
        },
        {
            "name": "JO",
            "baseName": "JO",
            "type": "MovieWatchProviders200ResponseResultsJO"
        },
        {
            "name": "JP",
            "baseName": "JP",
            "type": "MovieWatchProviders200ResponseResultsJP"
        },
        {
            "name": "KR",
            "baseName": "KR",
            "type": "MovieWatchProviders200ResponseResultsKR"
        },
        {
            "name": "KW",
            "baseName": "KW",
            "type": "MovieWatchProviders200ResponseResultsKW"
        },
        {
            "name": "LB",
            "baseName": "LB",
            "type": "MovieWatchProviders200ResponseResultsLB"
        },
        {
            "name": "LI",
            "baseName": "LI",
            "type": "MovieWatchProviders200ResponseResultsLI"
        },
        {
            "name": "LT",
            "baseName": "LT",
            "type": "MovieWatchProviders200ResponseResultsLT"
        },
        {
            "name": "LV",
            "baseName": "LV",
            "type": "MovieWatchProviders200ResponseResultsLV"
        },
        {
            "name": "MD",
            "baseName": "MD",
            "type": "MovieWatchProviders200ResponseResultsMD"
        },
        {
            "name": "MK",
            "baseName": "MK",
            "type": "MovieWatchProviders200ResponseResultsMK"
        },
        {
            "name": "MT",
            "baseName": "MT",
            "type": "MovieWatchProviders200ResponseResultsMT"
        },
        {
            "name": "MU",
            "baseName": "MU",
            "type": "MovieWatchProviders200ResponseResultsMU"
        },
        {
            "name": "MX",
            "baseName": "MX",
            "type": "MovieWatchProviders200ResponseResultsMX"
        },
        {
            "name": "MY",
            "baseName": "MY",
            "type": "MovieWatchProviders200ResponseResultsMY"
        },
        {
            "name": "MZ",
            "baseName": "MZ",
            "type": "MovieWatchProviders200ResponseResultsMZ"
        },
        {
            "name": "NL",
            "baseName": "NL",
            "type": "MovieWatchProviders200ResponseResultsNL"
        },
        {
            "name": "NO",
            "baseName": "NO",
            "type": "MovieWatchProviders200ResponseResultsNO"
        },
        {
            "name": "NZ",
            "baseName": "NZ",
            "type": "MovieWatchProviders200ResponseResultsNZ"
        },
        {
            "name": "OM",
            "baseName": "OM",
            "type": "MovieWatchProviders200ResponseResultsOM"
        },
        {
            "name": "PA",
            "baseName": "PA",
            "type": "MovieWatchProviders200ResponseResultsPA"
        },
        {
            "name": "PE",
            "baseName": "PE",
            "type": "MovieWatchProviders200ResponseResultsPE"
        },
        {
            "name": "PH",
            "baseName": "PH",
            "type": "MovieWatchProviders200ResponseResultsPH"
        },
        {
            "name": "PK",
            "baseName": "PK",
            "type": "MovieWatchProviders200ResponseResultsPK"
        },
        {
            "name": "PL",
            "baseName": "PL",
            "type": "MovieWatchProviders200ResponseResultsPL"
        },
        {
            "name": "PS",
            "baseName": "PS",
            "type": "MovieWatchProviders200ResponseResultsPS"
        },
        {
            "name": "PT",
            "baseName": "PT",
            "type": "MovieWatchProviders200ResponseResultsPT"
        },
        {
            "name": "PY",
            "baseName": "PY",
            "type": "MovieWatchProviders200ResponseResultsPY"
        },
        {
            "name": "QA",
            "baseName": "QA",
            "type": "MovieWatchProviders200ResponseResultsQA"
        },
        {
            "name": "RO",
            "baseName": "RO",
            "type": "MovieWatchProviders200ResponseResultsRO"
        },
        {
            "name": "RS",
            "baseName": "RS",
            "type": "MovieWatchProviders200ResponseResultsRS"
        },
        {
            "name": "RU",
            "baseName": "RU",
            "type": "MovieWatchProviders200ResponseResultsRU"
        },
        {
            "name": "SA",
            "baseName": "SA",
            "type": "MovieWatchProviders200ResponseResultsSA"
        },
        {
            "name": "SE",
            "baseName": "SE",
            "type": "MovieWatchProviders200ResponseResultsSE"
        },
        {
            "name": "SG",
            "baseName": "SG",
            "type": "MovieWatchProviders200ResponseResultsSG"
        },
        {
            "name": "SI",
            "baseName": "SI",
            "type": "MovieWatchProviders200ResponseResultsSI"
        },
        {
            "name": "SK",
            "baseName": "SK",
            "type": "MovieWatchProviders200ResponseResultsSK"
        },
        {
            "name": "SM",
            "baseName": "SM",
            "type": "MovieWatchProviders200ResponseResultsSM"
        },
        {
            "name": "SV",
            "baseName": "SV",
            "type": "MovieWatchProviders200ResponseResultsSV"
        },
        {
            "name": "TH",
            "baseName": "TH",
            "type": "MovieWatchProviders200ResponseResultsTH"
        },
        {
            "name": "TR",
            "baseName": "TR",
            "type": "MovieWatchProviders200ResponseResultsTR"
        },
        {
            "name": "TT",
            "baseName": "TT",
            "type": "MovieWatchProviders200ResponseResultsTT"
        },
        {
            "name": "TW",
            "baseName": "TW",
            "type": "MovieWatchProviders200ResponseResultsTW"
        },
        {
            "name": "UG",
            "baseName": "UG",
            "type": "MovieWatchProviders200ResponseResultsUG"
        },
        {
            "name": "US",
            "baseName": "US",
            "type": "MovieWatchProviders200ResponseResultsUS"
        },
        {
            "name": "UY",
            "baseName": "UY",
            "type": "MovieWatchProviders200ResponseResultsUY"
        },
        {
            "name": "VE",
            "baseName": "VE",
            "type": "MovieWatchProviders200ResponseResultsVE"
        },
        {
            "name": "YE",
            "baseName": "YE",
            "type": "MovieWatchProviders200ResponseResultsYE"
        },
        {
            "name": "ZA",
            "baseName": "ZA",
            "type": "MovieWatchProviders200ResponseResultsZA"
        }    ];

    static getAttributeTypeMap() {
        return MovieWatchProviders200ResponseResults.attributeTypeMap;
    }
}

