/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieWatchProviders200ResponseResultsPERentInner } from './movieWatchProviders200ResponseResultsPERentInner';
import { MovieWatchProviders200ResponseResultsPLFlatrateInner } from './movieWatchProviders200ResponseResultsPLFlatrateInner';

export class MovieWatchProviders200ResponseResultsTR {
    'link'?: string;
    'rent'?: Array<MovieWatchProviders200ResponseResultsPERentInner>;
    'flatrate'?: Array<MovieWatchProviders200ResponseResultsPLFlatrateInner>;
    'buy'?: Array<MovieWatchProviders200ResponseResultsPERentInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "rent",
            "baseName": "rent",
            "type": "Array<MovieWatchProviders200ResponseResultsPERentInner>"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<MovieWatchProviders200ResponseResultsPLFlatrateInner>"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<MovieWatchProviders200ResponseResultsPERentInner>"
        }    ];

    static getAttributeTypeMap() {
        return MovieWatchProviders200ResponseResultsTR.attributeTypeMap;
    }
}

