/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieWatchProviders200ResponseResultsBEFlatrateInner } from './movieWatchProviders200ResponseResultsBEFlatrateInner';
import { MovieWatchProviders200ResponseResultsPERentInner } from './movieWatchProviders200ResponseResultsPERentInner';
import { MovieWatchProviders200ResponseResultsPTRentInner } from './movieWatchProviders200ResponseResultsPTRentInner';

export class MovieWatchProviders200ResponseResultsPT {
    'link'?: string;
    'buy'?: Array<MovieWatchProviders200ResponseResultsPERentInner>;
    'rent'?: Array<MovieWatchProviders200ResponseResultsPTRentInner>;
    'flatrate'?: Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<MovieWatchProviders200ResponseResultsPERentInner>"
        },
        {
            "name": "rent",
            "baseName": "rent",
            "type": "Array<MovieWatchProviders200ResponseResultsPTRentInner>"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<MovieWatchProviders200ResponseResultsBEFlatrateInner>"
        }    ];

    static getAttributeTypeMap() {
        return MovieWatchProviders200ResponseResultsPT.attributeTypeMap;
    }
}

