/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieDetails200ResponseGenresInner } from './movieDetails200ResponseGenresInner';
import { MovieDetails200ResponseProductionCompaniesInner } from './movieDetails200ResponseProductionCompaniesInner';
import { MovieDetails200ResponseProductionCountriesInner } from './movieDetails200ResponseProductionCountriesInner';
import { MovieDetails200ResponseSpokenLanguagesInner } from './movieDetails200ResponseSpokenLanguagesInner';

export class MovieDetails200Response {
    'adult'?: boolean = true;
    'backdrop_path'?: string;
    'belongs_to_collection'?: any | null;
    'budget'?: number = 0;
    'genres'?: Array<MovieDetails200ResponseGenresInner>;
    'homepage'?: string;
    'id'?: number = 0;
    'imdb_id'?: string;
    'original_language'?: string;
    'original_title'?: string;
    'overview'?: string;
    'popularity'?: number = 0;
    'poster_path'?: string;
    'production_companies'?: Array<MovieDetails200ResponseProductionCompaniesInner>;
    'production_countries'?: Array<MovieDetails200ResponseProductionCountriesInner>;
    'release_date'?: string;
    'revenue'?: number = 0;
    'runtime'?: number = 0;
    'spoken_languages'?: Array<MovieDetails200ResponseSpokenLanguagesInner>;
    'status'?: string;
    'tagline'?: string;
    'title'?: string;
    'video'?: boolean = true;
    'vote_average'?: number = 0;
    'vote_count'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "adult",
            "baseName": "adult",
            "type": "boolean"
        },
        {
            "name": "backdrop_path",
            "baseName": "backdrop_path",
            "type": "string"
        },
        {
            "name": "belongs_to_collection",
            "baseName": "belongs_to_collection",
            "type": "any"
        },
        {
            "name": "budget",
            "baseName": "budget",
            "type": "number"
        },
        {
            "name": "genres",
            "baseName": "genres",
            "type": "Array<MovieDetails200ResponseGenresInner>"
        },
        {
            "name": "homepage",
            "baseName": "homepage",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "imdb_id",
            "baseName": "imdb_id",
            "type": "string"
        },
        {
            "name": "original_language",
            "baseName": "original_language",
            "type": "string"
        },
        {
            "name": "original_title",
            "baseName": "original_title",
            "type": "string"
        },
        {
            "name": "overview",
            "baseName": "overview",
            "type": "string"
        },
        {
            "name": "popularity",
            "baseName": "popularity",
            "type": "number"
        },
        {
            "name": "poster_path",
            "baseName": "poster_path",
            "type": "string"
        },
        {
            "name": "production_companies",
            "baseName": "production_companies",
            "type": "Array<MovieDetails200ResponseProductionCompaniesInner>"
        },
        {
            "name": "production_countries",
            "baseName": "production_countries",
            "type": "Array<MovieDetails200ResponseProductionCountriesInner>"
        },
        {
            "name": "release_date",
            "baseName": "release_date",
            "type": "string"
        },
        {
            "name": "revenue",
            "baseName": "revenue",
            "type": "number"
        },
        {
            "name": "runtime",
            "baseName": "runtime",
            "type": "number"
        },
        {
            "name": "spoken_languages",
            "baseName": "spoken_languages",
            "type": "Array<MovieDetails200ResponseSpokenLanguagesInner>"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "tagline",
            "baseName": "tagline",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "video",
            "baseName": "video",
            "type": "boolean"
        },
        {
            "name": "vote_average",
            "baseName": "vote_average",
            "type": "number"
        },
        {
            "name": "vote_count",
            "baseName": "vote_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MovieDetails200Response.attributeTypeMap;
    }
}

