/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MovieReleaseDates200ResponseResultsInnerReleaseDatesInner {
    'certification'?: string;
    'descriptors'?: Array<string>;
    'iso_639_1'?: string;
    'note'?: string;
    'release_date'?: string;
    'type'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "certification",
            "baseName": "certification",
            "type": "string"
        },
        {
            "name": "descriptors",
            "baseName": "descriptors",
            "type": "Array<string>"
        },
        {
            "name": "iso_639_1",
            "baseName": "iso_639_1",
            "type": "string"
        },
        {
            "name": "note",
            "baseName": "note",
            "type": "string"
        },
        {
            "name": "release_date",
            "baseName": "release_date",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MovieReleaseDates200ResponseResultsInnerReleaseDatesInner.attributeTypeMap;
    }
}

