/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieWatchProviders200ResponseResultsBHBuyInner } from './movieWatchProviders200ResponseResultsBHBuyInner';
import { MovieWatchProviders200ResponseResultsMDFlatrateInner } from './movieWatchProviders200ResponseResultsMDFlatrateInner';

export class MovieWatchProviders200ResponseResultsMD {
    'link'?: string;
    'buy'?: Array<MovieWatchProviders200ResponseResultsBHBuyInner>;
    'flatrate'?: Array<MovieWatchProviders200ResponseResultsMDFlatrateInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<MovieWatchProviders200ResponseResultsBHBuyInner>"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<MovieWatchProviders200ResponseResultsMDFlatrateInner>"
        }    ];

    static getAttributeTypeMap() {
        return MovieWatchProviders200ResponseResultsMD.attributeTypeMap;
    }
}

