/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PersonImages200ResponseProfilesInner } from './personImages200ResponseProfilesInner';

export class PersonImages200Response {
    'id'?: number = 0;
    'profiles'?: Array<PersonImages200ResponseProfilesInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "profiles",
            "baseName": "profiles",
            "type": "Array<PersonImages200ResponseProfilesInner>"
        }    ];

    static getAttributeTypeMap() {
        return PersonImages200Response.attributeTypeMap;
    }
}

