/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PersonCombinedCredits200ResponseCastInner } from './personCombinedCredits200ResponseCastInner';
import { PersonCombinedCredits200ResponseCrewInner } from './personCombinedCredits200ResponseCrewInner';

export class PersonCombinedCredits200Response {
    'cast'?: Array<PersonCombinedCredits200ResponseCastInner>;
    'crew'?: Array<PersonCombinedCredits200ResponseCrewInner>;
    'id'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cast",
            "baseName": "cast",
            "type": "Array<PersonCombinedCredits200ResponseCastInner>"
        },
        {
            "name": "crew",
            "baseName": "crew",
            "type": "Array<PersonCombinedCredits200ResponseCrewInner>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PersonCombinedCredits200Response.attributeTypeMap;
    }
}

