/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PersonLatestId200Response {
    'adult'?: boolean = true;
    'also_known_as'?: Array<string>;
    'biography'?: string;
    'birthday'?: any | null;
    'deathday'?: any | null;
    'gender'?: number = 0;
    'homepage'?: any | null;
    'id'?: number = 0;
    'imdb_id'?: any | null;
    'known_for_department'?: any | null;
    'name'?: string;
    'place_of_birth'?: any | null;
    'popularity'?: number = 0;
    'profile_path'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "adult",
            "baseName": "adult",
            "type": "boolean"
        },
        {
            "name": "also_known_as",
            "baseName": "also_known_as",
            "type": "Array<string>"
        },
        {
            "name": "biography",
            "baseName": "biography",
            "type": "string"
        },
        {
            "name": "birthday",
            "baseName": "birthday",
            "type": "any"
        },
        {
            "name": "deathday",
            "baseName": "deathday",
            "type": "any"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "number"
        },
        {
            "name": "homepage",
            "baseName": "homepage",
            "type": "any"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "imdb_id",
            "baseName": "imdb_id",
            "type": "any"
        },
        {
            "name": "known_for_department",
            "baseName": "known_for_department",
            "type": "any"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "place_of_birth",
            "baseName": "place_of_birth",
            "type": "any"
        },
        {
            "name": "popularity",
            "baseName": "popularity",
            "type": "number"
        },
        {
            "name": "profile_path",
            "baseName": "profile_path",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return PersonLatestId200Response.attributeTypeMap;
    }
}

