/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReviewDetails200ResponseAuthorDetails {
    'name'?: string;
    'username'?: string;
    'avatar_path'?: string;
    'rating'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string"
        },
        {
            "name": "avatar_path",
            "baseName": "avatar_path",
            "type": "string"
        },
        {
            "name": "rating",
            "baseName": "rating",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ReviewDetails200ResponseAuthorDetails.attributeTypeMap;
    }
}

