/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ReviewDetails200ResponseAuthorDetails } from './reviewDetails200ResponseAuthorDetails';

export class ReviewDetails200Response {
    'id'?: string;
    'author'?: string;
    'author_details'?: ReviewDetails200ResponseAuthorDetails;
    'content'?: string;
    'created_at'?: string;
    'iso_639_1'?: string;
    'media_id'?: number = 0;
    'media_title'?: string;
    'media_type'?: string;
    'updated_at'?: string;
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "string"
        },
        {
            "name": "author_details",
            "baseName": "author_details",
            "type": "ReviewDetails200ResponseAuthorDetails"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "created_at",
            "baseName": "created_at",
            "type": "string"
        },
        {
            "name": "iso_639_1",
            "baseName": "iso_639_1",
            "type": "string"
        },
        {
            "name": "media_id",
            "baseName": "media_id",
            "type": "number"
        },
        {
            "name": "media_title",
            "baseName": "media_title",
            "type": "string"
        },
        {
            "name": "media_type",
            "baseName": "media_type",
            "type": "string"
        },
        {
            "name": "updated_at",
            "baseName": "updated_at",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReviewDetails200Response.attributeTypeMap;
    }
}

