/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvEpisodeImages200ResponseStillsInner } from './tvEpisodeImages200ResponseStillsInner';

export class TvEpisodeImages200Response {
    'id'?: number = 0;
    'stills'?: Array<TvEpisodeImages200ResponseStillsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "stills",
            "baseName": "stills",
            "type": "Array<TvEpisodeImages200ResponseStillsInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvEpisodeImages200Response.attributeTypeMap;
    }
}

