/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeriesWatchProviders200ResponseResultsJPBuyInner } from './tvSeriesWatchProviders200ResponseResultsJPBuyInner';
import { TvSeriesWatchProviders200ResponseResultsJPFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsJPFlatrateInner';

export class TvSeriesWatchProviders200ResponseResultsJP {
    'link'?: string;
    'flatrate'?: Array<TvSeriesWatchProviders200ResponseResultsJPFlatrateInner>;
    'buy'?: Array<TvSeriesWatchProviders200ResponseResultsJPBuyInner>;
    'rent'?: Array<TvSeriesWatchProviders200ResponseResultsJPBuyInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsJPFlatrateInner>"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsJPBuyInner>"
        },
        {
            "name": "rent",
            "baseName": "rent",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsJPBuyInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesWatchProviders200ResponseResultsJP.attributeTypeMap;
    }
}

