/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeriesWatchProviders200ResponseResultsRUAdsInner } from './tvSeriesWatchProviders200ResponseResultsRUAdsInner';
import { TvSeriesWatchProviders200ResponseResultsRUFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsRUFlatrateInner';

export class TvSeriesWatchProviders200ResponseResultsRU {
    'link'?: string;
    'flatrate'?: Array<TvSeriesWatchProviders200ResponseResultsRUFlatrateInner>;
    'ads'?: Array<TvSeriesWatchProviders200ResponseResultsRUAdsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsRUFlatrateInner>"
        },
        {
            "name": "ads",
            "baseName": "ads",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsRUAdsInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesWatchProviders200ResponseResultsRU.attributeTypeMap;
    }
}

