/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeasonDetails200ResponseEpisodesInner } from './tvSeasonDetails200ResponseEpisodesInner';

export class TvSeasonDetails200Response {
    '_id'?: string;
    'air_date'?: string;
    'episodes'?: Array<TvSeasonDetails200ResponseEpisodesInner>;
    'name'?: string;
    'overview'?: string;
    'id'?: number = 0;
    'poster_path'?: string;
    'season_number'?: number = 0;
    'vote_average'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_id",
            "baseName": "_id",
            "type": "string"
        },
        {
            "name": "air_date",
            "baseName": "air_date",
            "type": "string"
        },
        {
            "name": "episodes",
            "baseName": "episodes",
            "type": "Array<TvSeasonDetails200ResponseEpisodesInner>"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "overview",
            "baseName": "overview",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "poster_path",
            "baseName": "poster_path",
            "type": "string"
        },
        {
            "name": "season_number",
            "baseName": "season_number",
            "type": "number"
        },
        {
            "name": "vote_average",
            "baseName": "vote_average",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TvSeasonDetails200Response.attributeTypeMap;
    }
}

