/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeriesWatchProviders200ResponseResultsAE } from './tvSeriesWatchProviders200ResponseResultsAE';
import { TvSeriesWatchProviders200ResponseResultsAR } from './tvSeriesWatchProviders200ResponseResultsAR';
import { TvSeriesWatchProviders200ResponseResultsAT } from './tvSeriesWatchProviders200ResponseResultsAT';
import { TvSeriesWatchProviders200ResponseResultsAU } from './tvSeriesWatchProviders200ResponseResultsAU';
import { TvSeriesWatchProviders200ResponseResultsBA } from './tvSeriesWatchProviders200ResponseResultsBA';
import { TvSeriesWatchProviders200ResponseResultsBB } from './tvSeriesWatchProviders200ResponseResultsBB';
import { TvSeriesWatchProviders200ResponseResultsBE } from './tvSeriesWatchProviders200ResponseResultsBE';
import { TvSeriesWatchProviders200ResponseResultsBG } from './tvSeriesWatchProviders200ResponseResultsBG';
import { TvSeriesWatchProviders200ResponseResultsBO } from './tvSeriesWatchProviders200ResponseResultsBO';
import { TvSeriesWatchProviders200ResponseResultsBR } from './tvSeriesWatchProviders200ResponseResultsBR';
import { TvSeriesWatchProviders200ResponseResultsBS } from './tvSeriesWatchProviders200ResponseResultsBS';
import { TvSeriesWatchProviders200ResponseResultsCA } from './tvSeriesWatchProviders200ResponseResultsCA';
import { TvSeriesWatchProviders200ResponseResultsCH } from './tvSeriesWatchProviders200ResponseResultsCH';
import { TvSeriesWatchProviders200ResponseResultsCI } from './tvSeriesWatchProviders200ResponseResultsCI';
import { TvSeriesWatchProviders200ResponseResultsCL } from './tvSeriesWatchProviders200ResponseResultsCL';
import { TvSeriesWatchProviders200ResponseResultsCO } from './tvSeriesWatchProviders200ResponseResultsCO';
import { TvSeriesWatchProviders200ResponseResultsCR } from './tvSeriesWatchProviders200ResponseResultsCR';
import { TvSeriesWatchProviders200ResponseResultsCZ } from './tvSeriesWatchProviders200ResponseResultsCZ';
import { TvSeriesWatchProviders200ResponseResultsDE } from './tvSeriesWatchProviders200ResponseResultsDE';
import { TvSeriesWatchProviders200ResponseResultsDK } from './tvSeriesWatchProviders200ResponseResultsDK';
import { TvSeriesWatchProviders200ResponseResultsDO } from './tvSeriesWatchProviders200ResponseResultsDO';
import { TvSeriesWatchProviders200ResponseResultsDZ } from './tvSeriesWatchProviders200ResponseResultsDZ';
import { TvSeriesWatchProviders200ResponseResultsEC } from './tvSeriesWatchProviders200ResponseResultsEC';
import { TvSeriesWatchProviders200ResponseResultsEG } from './tvSeriesWatchProviders200ResponseResultsEG';
import { TvSeriesWatchProviders200ResponseResultsES } from './tvSeriesWatchProviders200ResponseResultsES';
import { TvSeriesWatchProviders200ResponseResultsFI } from './tvSeriesWatchProviders200ResponseResultsFI';
import { TvSeriesWatchProviders200ResponseResultsFR } from './tvSeriesWatchProviders200ResponseResultsFR';
import { TvSeriesWatchProviders200ResponseResultsGB } from './tvSeriesWatchProviders200ResponseResultsGB';
import { TvSeriesWatchProviders200ResponseResultsGF } from './tvSeriesWatchProviders200ResponseResultsGF';
import { TvSeriesWatchProviders200ResponseResultsGH } from './tvSeriesWatchProviders200ResponseResultsGH';
import { TvSeriesWatchProviders200ResponseResultsGQ } from './tvSeriesWatchProviders200ResponseResultsGQ';
import { TvSeriesWatchProviders200ResponseResultsGT } from './tvSeriesWatchProviders200ResponseResultsGT';
import { TvSeriesWatchProviders200ResponseResultsHK } from './tvSeriesWatchProviders200ResponseResultsHK';
import { TvSeriesWatchProviders200ResponseResultsHN } from './tvSeriesWatchProviders200ResponseResultsHN';
import { TvSeriesWatchProviders200ResponseResultsHR } from './tvSeriesWatchProviders200ResponseResultsHR';
import { TvSeriesWatchProviders200ResponseResultsHU } from './tvSeriesWatchProviders200ResponseResultsHU';
import { TvSeriesWatchProviders200ResponseResultsID } from './tvSeriesWatchProviders200ResponseResultsID';
import { TvSeriesWatchProviders200ResponseResultsIE } from './tvSeriesWatchProviders200ResponseResultsIE';
import { TvSeriesWatchProviders200ResponseResultsIL } from './tvSeriesWatchProviders200ResponseResultsIL';
import { TvSeriesWatchProviders200ResponseResultsIQ } from './tvSeriesWatchProviders200ResponseResultsIQ';
import { TvSeriesWatchProviders200ResponseResultsIT } from './tvSeriesWatchProviders200ResponseResultsIT';
import { TvSeriesWatchProviders200ResponseResultsJM } from './tvSeriesWatchProviders200ResponseResultsJM';
import { TvSeriesWatchProviders200ResponseResultsJP } from './tvSeriesWatchProviders200ResponseResultsJP';
import { TvSeriesWatchProviders200ResponseResultsKE } from './tvSeriesWatchProviders200ResponseResultsKE';
import { TvSeriesWatchProviders200ResponseResultsKR } from './tvSeriesWatchProviders200ResponseResultsKR';
import { TvSeriesWatchProviders200ResponseResultsLB } from './tvSeriesWatchProviders200ResponseResultsLB';
import { TvSeriesWatchProviders200ResponseResultsLT } from './tvSeriesWatchProviders200ResponseResultsLT';
import { TvSeriesWatchProviders200ResponseResultsLY } from './tvSeriesWatchProviders200ResponseResultsLY';
import { TvSeriesWatchProviders200ResponseResultsMD } from './tvSeriesWatchProviders200ResponseResultsMD';
import { TvSeriesWatchProviders200ResponseResultsMK } from './tvSeriesWatchProviders200ResponseResultsMK';
import { TvSeriesWatchProviders200ResponseResultsMU } from './tvSeriesWatchProviders200ResponseResultsMU';
import { TvSeriesWatchProviders200ResponseResultsMX } from './tvSeriesWatchProviders200ResponseResultsMX';
import { TvSeriesWatchProviders200ResponseResultsMY } from './tvSeriesWatchProviders200ResponseResultsMY';
import { TvSeriesWatchProviders200ResponseResultsMZ } from './tvSeriesWatchProviders200ResponseResultsMZ';
import { TvSeriesWatchProviders200ResponseResultsNE } from './tvSeriesWatchProviders200ResponseResultsNE';
import { TvSeriesWatchProviders200ResponseResultsNG } from './tvSeriesWatchProviders200ResponseResultsNG';
import { TvSeriesWatchProviders200ResponseResultsNL } from './tvSeriesWatchProviders200ResponseResultsNL';
import { TvSeriesWatchProviders200ResponseResultsNO } from './tvSeriesWatchProviders200ResponseResultsNO';
import { TvSeriesWatchProviders200ResponseResultsNZ } from './tvSeriesWatchProviders200ResponseResultsNZ';
import { TvSeriesWatchProviders200ResponseResultsPA } from './tvSeriesWatchProviders200ResponseResultsPA';
import { TvSeriesWatchProviders200ResponseResultsPE } from './tvSeriesWatchProviders200ResponseResultsPE';
import { TvSeriesWatchProviders200ResponseResultsPH } from './tvSeriesWatchProviders200ResponseResultsPH';
import { TvSeriesWatchProviders200ResponseResultsPL } from './tvSeriesWatchProviders200ResponseResultsPL';
import { TvSeriesWatchProviders200ResponseResultsPS } from './tvSeriesWatchProviders200ResponseResultsPS';
import { TvSeriesWatchProviders200ResponseResultsPT } from './tvSeriesWatchProviders200ResponseResultsPT';
import { TvSeriesWatchProviders200ResponseResultsPY } from './tvSeriesWatchProviders200ResponseResultsPY';
import { TvSeriesWatchProviders200ResponseResultsRO } from './tvSeriesWatchProviders200ResponseResultsRO';
import { TvSeriesWatchProviders200ResponseResultsRS } from './tvSeriesWatchProviders200ResponseResultsRS';
import { TvSeriesWatchProviders200ResponseResultsRU } from './tvSeriesWatchProviders200ResponseResultsRU';
import { TvSeriesWatchProviders200ResponseResultsSA } from './tvSeriesWatchProviders200ResponseResultsSA';
import { TvSeriesWatchProviders200ResponseResultsSC } from './tvSeriesWatchProviders200ResponseResultsSC';
import { TvSeriesWatchProviders200ResponseResultsSE } from './tvSeriesWatchProviders200ResponseResultsSE';
import { TvSeriesWatchProviders200ResponseResultsSG } from './tvSeriesWatchProviders200ResponseResultsSG';
import { TvSeriesWatchProviders200ResponseResultsSI } from './tvSeriesWatchProviders200ResponseResultsSI';
import { TvSeriesWatchProviders200ResponseResultsSK } from './tvSeriesWatchProviders200ResponseResultsSK';
import { TvSeriesWatchProviders200ResponseResultsSN } from './tvSeriesWatchProviders200ResponseResultsSN';
import { TvSeriesWatchProviders200ResponseResultsSV } from './tvSeriesWatchProviders200ResponseResultsSV';
import { TvSeriesWatchProviders200ResponseResultsTH } from './tvSeriesWatchProviders200ResponseResultsTH';
import { TvSeriesWatchProviders200ResponseResultsTR } from './tvSeriesWatchProviders200ResponseResultsTR';
import { TvSeriesWatchProviders200ResponseResultsTT } from './tvSeriesWatchProviders200ResponseResultsTT';
import { TvSeriesWatchProviders200ResponseResultsTW } from './tvSeriesWatchProviders200ResponseResultsTW';
import { TvSeriesWatchProviders200ResponseResultsTZ } from './tvSeriesWatchProviders200ResponseResultsTZ';
import { TvSeriesWatchProviders200ResponseResultsUG } from './tvSeriesWatchProviders200ResponseResultsUG';
import { TvSeriesWatchProviders200ResponseResultsUS } from './tvSeriesWatchProviders200ResponseResultsUS';
import { TvSeriesWatchProviders200ResponseResultsUY } from './tvSeriesWatchProviders200ResponseResultsUY';
import { TvSeriesWatchProviders200ResponseResultsVE } from './tvSeriesWatchProviders200ResponseResultsVE';
import { TvSeriesWatchProviders200ResponseResultsZA } from './tvSeriesWatchProviders200ResponseResultsZA';
import { TvSeriesWatchProviders200ResponseResultsZM } from './tvSeriesWatchProviders200ResponseResultsZM';

export class TvSeriesWatchProviders200ResponseResults {
    'AE'?: TvSeriesWatchProviders200ResponseResultsAE;
    'AR'?: TvSeriesWatchProviders200ResponseResultsAR;
    'AT'?: TvSeriesWatchProviders200ResponseResultsAT;
    'AU'?: TvSeriesWatchProviders200ResponseResultsAU;
    'BA'?: TvSeriesWatchProviders200ResponseResultsBA;
    'BB'?: TvSeriesWatchProviders200ResponseResultsBB;
    'BE'?: TvSeriesWatchProviders200ResponseResultsBE;
    'BG'?: TvSeriesWatchProviders200ResponseResultsBG;
    'BO'?: TvSeriesWatchProviders200ResponseResultsBO;
    'BR'?: TvSeriesWatchProviders200ResponseResultsBR;
    'BS'?: TvSeriesWatchProviders200ResponseResultsBS;
    'CA'?: TvSeriesWatchProviders200ResponseResultsCA;
    'CH'?: TvSeriesWatchProviders200ResponseResultsCH;
    'CI'?: TvSeriesWatchProviders200ResponseResultsCI;
    'CL'?: TvSeriesWatchProviders200ResponseResultsCL;
    'CO'?: TvSeriesWatchProviders200ResponseResultsCO;
    'CR'?: TvSeriesWatchProviders200ResponseResultsCR;
    'CZ'?: TvSeriesWatchProviders200ResponseResultsCZ;
    'DE'?: TvSeriesWatchProviders200ResponseResultsDE;
    'DK'?: TvSeriesWatchProviders200ResponseResultsDK;
    'DO'?: TvSeriesWatchProviders200ResponseResultsDO;
    'DZ'?: TvSeriesWatchProviders200ResponseResultsDZ;
    'EC'?: TvSeriesWatchProviders200ResponseResultsEC;
    'EG'?: TvSeriesWatchProviders200ResponseResultsEG;
    'ES'?: TvSeriesWatchProviders200ResponseResultsES;
    'FI'?: TvSeriesWatchProviders200ResponseResultsFI;
    'FR'?: TvSeriesWatchProviders200ResponseResultsFR;
    'GB'?: TvSeriesWatchProviders200ResponseResultsGB;
    'GF'?: TvSeriesWatchProviders200ResponseResultsGF;
    'GH'?: TvSeriesWatchProviders200ResponseResultsGH;
    'GQ'?: TvSeriesWatchProviders200ResponseResultsGQ;
    'GT'?: TvSeriesWatchProviders200ResponseResultsGT;
    'HK'?: TvSeriesWatchProviders200ResponseResultsHK;
    'HN'?: TvSeriesWatchProviders200ResponseResultsHN;
    'HR'?: TvSeriesWatchProviders200ResponseResultsHR;
    'HU'?: TvSeriesWatchProviders200ResponseResultsHU;
    'ID'?: TvSeriesWatchProviders200ResponseResultsID;
    'IE'?: TvSeriesWatchProviders200ResponseResultsIE;
    'IL'?: TvSeriesWatchProviders200ResponseResultsIL;
    'IQ'?: TvSeriesWatchProviders200ResponseResultsIQ;
    'IT'?: TvSeriesWatchProviders200ResponseResultsIT;
    'JM'?: TvSeriesWatchProviders200ResponseResultsJM;
    'JP'?: TvSeriesWatchProviders200ResponseResultsJP;
    'KE'?: TvSeriesWatchProviders200ResponseResultsKE;
    'KR'?: TvSeriesWatchProviders200ResponseResultsKR;
    'LB'?: TvSeriesWatchProviders200ResponseResultsLB;
    'LT'?: TvSeriesWatchProviders200ResponseResultsLT;
    'LY'?: TvSeriesWatchProviders200ResponseResultsLY;
    'MD'?: TvSeriesWatchProviders200ResponseResultsMD;
    'MK'?: TvSeriesWatchProviders200ResponseResultsMK;
    'MU'?: TvSeriesWatchProviders200ResponseResultsMU;
    'MX'?: TvSeriesWatchProviders200ResponseResultsMX;
    'MY'?: TvSeriesWatchProviders200ResponseResultsMY;
    'MZ'?: TvSeriesWatchProviders200ResponseResultsMZ;
    'NE'?: TvSeriesWatchProviders200ResponseResultsNE;
    'NG'?: TvSeriesWatchProviders200ResponseResultsNG;
    'NL'?: TvSeriesWatchProviders200ResponseResultsNL;
    'NO'?: TvSeriesWatchProviders200ResponseResultsNO;
    'NZ'?: TvSeriesWatchProviders200ResponseResultsNZ;
    'PA'?: TvSeriesWatchProviders200ResponseResultsPA;
    'PE'?: TvSeriesWatchProviders200ResponseResultsPE;
    'PH'?: TvSeriesWatchProviders200ResponseResultsPH;
    'PL'?: TvSeriesWatchProviders200ResponseResultsPL;
    'PS'?: TvSeriesWatchProviders200ResponseResultsPS;
    'PT'?: TvSeriesWatchProviders200ResponseResultsPT;
    'PY'?: TvSeriesWatchProviders200ResponseResultsPY;
    'RO'?: TvSeriesWatchProviders200ResponseResultsRO;
    'RS'?: TvSeriesWatchProviders200ResponseResultsRS;
    'RU'?: TvSeriesWatchProviders200ResponseResultsRU;
    'SA'?: TvSeriesWatchProviders200ResponseResultsSA;
    'SC'?: TvSeriesWatchProviders200ResponseResultsSC;
    'SE'?: TvSeriesWatchProviders200ResponseResultsSE;
    'SG'?: TvSeriesWatchProviders200ResponseResultsSG;
    'SI'?: TvSeriesWatchProviders200ResponseResultsSI;
    'SK'?: TvSeriesWatchProviders200ResponseResultsSK;
    'SN'?: TvSeriesWatchProviders200ResponseResultsSN;
    'SV'?: TvSeriesWatchProviders200ResponseResultsSV;
    'TH'?: TvSeriesWatchProviders200ResponseResultsTH;
    'TR'?: TvSeriesWatchProviders200ResponseResultsTR;
    'TT'?: TvSeriesWatchProviders200ResponseResultsTT;
    'TW'?: TvSeriesWatchProviders200ResponseResultsTW;
    'TZ'?: TvSeriesWatchProviders200ResponseResultsTZ;
    'UG'?: TvSeriesWatchProviders200ResponseResultsUG;
    'US'?: TvSeriesWatchProviders200ResponseResultsUS;
    'UY'?: TvSeriesWatchProviders200ResponseResultsUY;
    'VE'?: TvSeriesWatchProviders200ResponseResultsVE;
    'ZA'?: TvSeriesWatchProviders200ResponseResultsZA;
    'ZM'?: TvSeriesWatchProviders200ResponseResultsZM;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "AE",
            "baseName": "AE",
            "type": "TvSeriesWatchProviders200ResponseResultsAE"
        },
        {
            "name": "AR",
            "baseName": "AR",
            "type": "TvSeriesWatchProviders200ResponseResultsAR"
        },
        {
            "name": "AT",
            "baseName": "AT",
            "type": "TvSeriesWatchProviders200ResponseResultsAT"
        },
        {
            "name": "AU",
            "baseName": "AU",
            "type": "TvSeriesWatchProviders200ResponseResultsAU"
        },
        {
            "name": "BA",
            "baseName": "BA",
            "type": "TvSeriesWatchProviders200ResponseResultsBA"
        },
        {
            "name": "BB",
            "baseName": "BB",
            "type": "TvSeriesWatchProviders200ResponseResultsBB"
        },
        {
            "name": "BE",
            "baseName": "BE",
            "type": "TvSeriesWatchProviders200ResponseResultsBE"
        },
        {
            "name": "BG",
            "baseName": "BG",
            "type": "TvSeriesWatchProviders200ResponseResultsBG"
        },
        {
            "name": "BO",
            "baseName": "BO",
            "type": "TvSeriesWatchProviders200ResponseResultsBO"
        },
        {
            "name": "BR",
            "baseName": "BR",
            "type": "TvSeriesWatchProviders200ResponseResultsBR"
        },
        {
            "name": "BS",
            "baseName": "BS",
            "type": "TvSeriesWatchProviders200ResponseResultsBS"
        },
        {
            "name": "CA",
            "baseName": "CA",
            "type": "TvSeriesWatchProviders200ResponseResultsCA"
        },
        {
            "name": "CH",
            "baseName": "CH",
            "type": "TvSeriesWatchProviders200ResponseResultsCH"
        },
        {
            "name": "CI",
            "baseName": "CI",
            "type": "TvSeriesWatchProviders200ResponseResultsCI"
        },
        {
            "name": "CL",
            "baseName": "CL",
            "type": "TvSeriesWatchProviders200ResponseResultsCL"
        },
        {
            "name": "CO",
            "baseName": "CO",
            "type": "TvSeriesWatchProviders200ResponseResultsCO"
        },
        {
            "name": "CR",
            "baseName": "CR",
            "type": "TvSeriesWatchProviders200ResponseResultsCR"
        },
        {
            "name": "CZ",
            "baseName": "CZ",
            "type": "TvSeriesWatchProviders200ResponseResultsCZ"
        },
        {
            "name": "DE",
            "baseName": "DE",
            "type": "TvSeriesWatchProviders200ResponseResultsDE"
        },
        {
            "name": "DK",
            "baseName": "DK",
            "type": "TvSeriesWatchProviders200ResponseResultsDK"
        },
        {
            "name": "DO",
            "baseName": "DO",
            "type": "TvSeriesWatchProviders200ResponseResultsDO"
        },
        {
            "name": "DZ",
            "baseName": "DZ",
            "type": "TvSeriesWatchProviders200ResponseResultsDZ"
        },
        {
            "name": "EC",
            "baseName": "EC",
            "type": "TvSeriesWatchProviders200ResponseResultsEC"
        },
        {
            "name": "EG",
            "baseName": "EG",
            "type": "TvSeriesWatchProviders200ResponseResultsEG"
        },
        {
            "name": "ES",
            "baseName": "ES",
            "type": "TvSeriesWatchProviders200ResponseResultsES"
        },
        {
            "name": "FI",
            "baseName": "FI",
            "type": "TvSeriesWatchProviders200ResponseResultsFI"
        },
        {
            "name": "FR",
            "baseName": "FR",
            "type": "TvSeriesWatchProviders200ResponseResultsFR"
        },
        {
            "name": "GB",
            "baseName": "GB",
            "type": "TvSeriesWatchProviders200ResponseResultsGB"
        },
        {
            "name": "GF",
            "baseName": "GF",
            "type": "TvSeriesWatchProviders200ResponseResultsGF"
        },
        {
            "name": "GH",
            "baseName": "GH",
            "type": "TvSeriesWatchProviders200ResponseResultsGH"
        },
        {
            "name": "GQ",
            "baseName": "GQ",
            "type": "TvSeriesWatchProviders200ResponseResultsGQ"
        },
        {
            "name": "GT",
            "baseName": "GT",
            "type": "TvSeriesWatchProviders200ResponseResultsGT"
        },
        {
            "name": "HK",
            "baseName": "HK",
            "type": "TvSeriesWatchProviders200ResponseResultsHK"
        },
        {
            "name": "HN",
            "baseName": "HN",
            "type": "TvSeriesWatchProviders200ResponseResultsHN"
        },
        {
            "name": "HR",
            "baseName": "HR",
            "type": "TvSeriesWatchProviders200ResponseResultsHR"
        },
        {
            "name": "HU",
            "baseName": "HU",
            "type": "TvSeriesWatchProviders200ResponseResultsHU"
        },
        {
            "name": "ID",
            "baseName": "ID",
            "type": "TvSeriesWatchProviders200ResponseResultsID"
        },
        {
            "name": "IE",
            "baseName": "IE",
            "type": "TvSeriesWatchProviders200ResponseResultsIE"
        },
        {
            "name": "IL",
            "baseName": "IL",
            "type": "TvSeriesWatchProviders200ResponseResultsIL"
        },
        {
            "name": "IQ",
            "baseName": "IQ",
            "type": "TvSeriesWatchProviders200ResponseResultsIQ"
        },
        {
            "name": "IT",
            "baseName": "IT",
            "type": "TvSeriesWatchProviders200ResponseResultsIT"
        },
        {
            "name": "JM",
            "baseName": "JM",
            "type": "TvSeriesWatchProviders200ResponseResultsJM"
        },
        {
            "name": "JP",
            "baseName": "JP",
            "type": "TvSeriesWatchProviders200ResponseResultsJP"
        },
        {
            "name": "KE",
            "baseName": "KE",
            "type": "TvSeriesWatchProviders200ResponseResultsKE"
        },
        {
            "name": "KR",
            "baseName": "KR",
            "type": "TvSeriesWatchProviders200ResponseResultsKR"
        },
        {
            "name": "LB",
            "baseName": "LB",
            "type": "TvSeriesWatchProviders200ResponseResultsLB"
        },
        {
            "name": "LT",
            "baseName": "LT",
            "type": "TvSeriesWatchProviders200ResponseResultsLT"
        },
        {
            "name": "LY",
            "baseName": "LY",
            "type": "TvSeriesWatchProviders200ResponseResultsLY"
        },
        {
            "name": "MD",
            "baseName": "MD",
            "type": "TvSeriesWatchProviders200ResponseResultsMD"
        },
        {
            "name": "MK",
            "baseName": "MK",
            "type": "TvSeriesWatchProviders200ResponseResultsMK"
        },
        {
            "name": "MU",
            "baseName": "MU",
            "type": "TvSeriesWatchProviders200ResponseResultsMU"
        },
        {
            "name": "MX",
            "baseName": "MX",
            "type": "TvSeriesWatchProviders200ResponseResultsMX"
        },
        {
            "name": "MY",
            "baseName": "MY",
            "type": "TvSeriesWatchProviders200ResponseResultsMY"
        },
        {
            "name": "MZ",
            "baseName": "MZ",
            "type": "TvSeriesWatchProviders200ResponseResultsMZ"
        },
        {
            "name": "NE",
            "baseName": "NE",
            "type": "TvSeriesWatchProviders200ResponseResultsNE"
        },
        {
            "name": "NG",
            "baseName": "NG",
            "type": "TvSeriesWatchProviders200ResponseResultsNG"
        },
        {
            "name": "NL",
            "baseName": "NL",
            "type": "TvSeriesWatchProviders200ResponseResultsNL"
        },
        {
            "name": "NO",
            "baseName": "NO",
            "type": "TvSeriesWatchProviders200ResponseResultsNO"
        },
        {
            "name": "NZ",
            "baseName": "NZ",
            "type": "TvSeriesWatchProviders200ResponseResultsNZ"
        },
        {
            "name": "PA",
            "baseName": "PA",
            "type": "TvSeriesWatchProviders200ResponseResultsPA"
        },
        {
            "name": "PE",
            "baseName": "PE",
            "type": "TvSeriesWatchProviders200ResponseResultsPE"
        },
        {
            "name": "PH",
            "baseName": "PH",
            "type": "TvSeriesWatchProviders200ResponseResultsPH"
        },
        {
            "name": "PL",
            "baseName": "PL",
            "type": "TvSeriesWatchProviders200ResponseResultsPL"
        },
        {
            "name": "PS",
            "baseName": "PS",
            "type": "TvSeriesWatchProviders200ResponseResultsPS"
        },
        {
            "name": "PT",
            "baseName": "PT",
            "type": "TvSeriesWatchProviders200ResponseResultsPT"
        },
        {
            "name": "PY",
            "baseName": "PY",
            "type": "TvSeriesWatchProviders200ResponseResultsPY"
        },
        {
            "name": "RO",
            "baseName": "RO",
            "type": "TvSeriesWatchProviders200ResponseResultsRO"
        },
        {
            "name": "RS",
            "baseName": "RS",
            "type": "TvSeriesWatchProviders200ResponseResultsRS"
        },
        {
            "name": "RU",
            "baseName": "RU",
            "type": "TvSeriesWatchProviders200ResponseResultsRU"
        },
        {
            "name": "SA",
            "baseName": "SA",
            "type": "TvSeriesWatchProviders200ResponseResultsSA"
        },
        {
            "name": "SC",
            "baseName": "SC",
            "type": "TvSeriesWatchProviders200ResponseResultsSC"
        },
        {
            "name": "SE",
            "baseName": "SE",
            "type": "TvSeriesWatchProviders200ResponseResultsSE"
        },
        {
            "name": "SG",
            "baseName": "SG",
            "type": "TvSeriesWatchProviders200ResponseResultsSG"
        },
        {
            "name": "SI",
            "baseName": "SI",
            "type": "TvSeriesWatchProviders200ResponseResultsSI"
        },
        {
            "name": "SK",
            "baseName": "SK",
            "type": "TvSeriesWatchProviders200ResponseResultsSK"
        },
        {
            "name": "SN",
            "baseName": "SN",
            "type": "TvSeriesWatchProviders200ResponseResultsSN"
        },
        {
            "name": "SV",
            "baseName": "SV",
            "type": "TvSeriesWatchProviders200ResponseResultsSV"
        },
        {
            "name": "TH",
            "baseName": "TH",
            "type": "TvSeriesWatchProviders200ResponseResultsTH"
        },
        {
            "name": "TR",
            "baseName": "TR",
            "type": "TvSeriesWatchProviders200ResponseResultsTR"
        },
        {
            "name": "TT",
            "baseName": "TT",
            "type": "TvSeriesWatchProviders200ResponseResultsTT"
        },
        {
            "name": "TW",
            "baseName": "TW",
            "type": "TvSeriesWatchProviders200ResponseResultsTW"
        },
        {
            "name": "TZ",
            "baseName": "TZ",
            "type": "TvSeriesWatchProviders200ResponseResultsTZ"
        },
        {
            "name": "UG",
            "baseName": "UG",
            "type": "TvSeriesWatchProviders200ResponseResultsUG"
        },
        {
            "name": "US",
            "baseName": "US",
            "type": "TvSeriesWatchProviders200ResponseResultsUS"
        },
        {
            "name": "UY",
            "baseName": "UY",
            "type": "TvSeriesWatchProviders200ResponseResultsUY"
        },
        {
            "name": "VE",
            "baseName": "VE",
            "type": "TvSeriesWatchProviders200ResponseResultsVE"
        },
        {
            "name": "ZA",
            "baseName": "ZA",
            "type": "TvSeriesWatchProviders200ResponseResultsZA"
        },
        {
            "name": "ZM",
            "baseName": "ZM",
            "type": "TvSeriesWatchProviders200ResponseResultsZM"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesWatchProviders200ResponseResults.attributeTypeMap;
    }
}

