/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeriesWatchProviders200ResponseResultsARFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsARFlatrateInner';
import { TvSeriesWatchProviders200ResponseResultsNOBuyInner } from './tvSeriesWatchProviders200ResponseResultsNOBuyInner';

export class TvSeasonWatchProviders200ResponseResultsNO {
    'link'?: string;
    'buy'?: Array<TvSeriesWatchProviders200ResponseResultsNOBuyInner>;
    'flatrate'?: Array<TvSeriesWatchProviders200ResponseResultsARFlatrateInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsNOBuyInner>"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsARFlatrateInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeasonWatchProviders200ResponseResultsNO.attributeTypeMap;
    }
}

