/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeriesWatchProviders200ResponseResultsPLFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsPLFlatrateInner';
import { TvSeriesWatchProviders200ResponseResultsPLRentInner } from './tvSeriesWatchProviders200ResponseResultsPLRentInner';

export class TvSeasonWatchProviders200ResponseResultsPL {
    'link'?: string;
    'rent'?: Array<TvSeriesWatchProviders200ResponseResultsPLRentInner>;
    'flatrate'?: Array<TvSeriesWatchProviders200ResponseResultsPLFlatrateInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "rent",
            "baseName": "rent",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsPLRentInner>"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsPLFlatrateInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeasonWatchProviders200ResponseResultsPL.attributeTypeMap;
    }
}

