/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieWatchProviders200ResponseResultsFRRentInner } from './movieWatchProviders200ResponseResultsFRRentInner';
import { TvSeriesWatchProviders200ResponseResultsFRFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsFRFlatrateInner';

export class TvSeasonWatchProviders200ResponseResultsFR {
    'link'?: string;
    'flatrate'?: Array<TvSeriesWatchProviders200ResponseResultsFRFlatrateInner>;
    'buy'?: Array<MovieWatchProviders200ResponseResultsFRRentInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsFRFlatrateInner>"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<MovieWatchProviders200ResponseResultsFRRentInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeasonWatchProviders200ResponseResultsFR.attributeTypeMap;
    }
}

