/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeriesChanges200ResponseChangesInner } from './tvSeriesChanges200ResponseChangesInner';

export class TvSeriesChanges200Response {
    'changes'?: Array<TvSeriesChanges200ResponseChangesInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "changes",
            "baseName": "changes",
            "type": "Array<TvSeriesChanges200ResponseChangesInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesChanges200Response.attributeTypeMap;
    }
}

