/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeasonChangesById200ResponseChangesInnerItemsInner } from './tvSeasonChangesById200ResponseChangesInnerItemsInner';

export class TvSeasonChangesById200ResponseChangesInner {
    'key'?: string;
    'items'?: Array<TvSeasonChangesById200ResponseChangesInnerItemsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<TvSeasonChangesById200ResponseChangesInnerItemsInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeasonChangesById200ResponseChangesInner.attributeTypeMap;
    }
}

