/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieWatchProviders200ResponseResultsPERentInner } from './movieWatchProviders200ResponseResultsPERentInner';
import { TvSeriesWatchProviders200ResponseResultsCHFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsCHFlatrateInner';

export class TvSeasonWatchProviders200ResponseResultsCH {
    'link'?: string;
    'buy'?: Array<MovieWatchProviders200ResponseResultsPERentInner>;
    'flatrate'?: Array<TvSeriesWatchProviders200ResponseResultsCHFlatrateInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<MovieWatchProviders200ResponseResultsPERentInner>"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsCHFlatrateInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeasonWatchProviders200ResponseResultsCH.attributeTypeMap;
    }
}

