/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeriesEpisodeGroups200ResponseResultsInner } from './tvSeriesEpisodeGroups200ResponseResultsInner';

export class TvSeriesEpisodeGroups200Response {
    'results'?: Array<TvSeriesEpisodeGroups200ResponseResultsInner>;
    'id'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<TvSeriesEpisodeGroups200ResponseResultsInner>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesEpisodeGroups200Response.attributeTypeMap;
    }
}

