/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeriesDetails200ResponseNetworksInner } from './tvSeriesDetails200ResponseNetworksInner';

export class TvSeriesEpisodeGroups200ResponseResultsInner {
    'description'?: string;
    'episode_count'?: number = 0;
    'group_count'?: number = 0;
    'id'?: string;
    'name'?: string;
    'network'?: TvSeriesDetails200ResponseNetworksInner;
    'type'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "episode_count",
            "baseName": "episode_count",
            "type": "number"
        },
        {
            "name": "group_count",
            "baseName": "group_count",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "network",
            "baseName": "network",
            "type": "TvSeriesDetails200ResponseNetworksInner"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesEpisodeGroups200ResponseResultsInner.attributeTypeMap;
    }
}

