/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeasonTranslations200ResponseTranslationsInner } from './tvSeasonTranslations200ResponseTranslationsInner';

export class TvSeasonTranslations200Response {
    'id'?: number = 0;
    'translations'?: Array<TvSeasonTranslations200ResponseTranslationsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "translations",
            "baseName": "translations",
            "type": "Array<TvSeasonTranslations200ResponseTranslationsInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeasonTranslations200Response.attributeTypeMap;
    }
}

