/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeriesChanges200ResponseChangesInnerItemsInner } from './tvSeriesChanges200ResponseChangesInnerItemsInner';

export class TvSeriesChanges200ResponseChangesInner {
    'key'?: string;
    'items'?: Array<TvSeriesChanges200ResponseChangesInnerItemsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<TvSeriesChanges200ResponseChangesInnerItemsInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesChanges200ResponseChangesInner.attributeTypeMap;
    }
}

