/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TvSeriesAggregateCredits200ResponseCrewInnerJobsInner {
    'credit_id'?: string;
    'job'?: string;
    'episode_count'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "credit_id",
            "baseName": "credit_id",
            "type": "string"
        },
        {
            "name": "job",
            "baseName": "job",
            "type": "string"
        },
        {
            "name": "episode_count",
            "baseName": "episode_count",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesAggregateCredits200ResponseCrewInnerJobsInner.attributeTypeMap;
    }
}

