/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieAccountStates200ResponseRated } from './movieAccountStates200ResponseRated';

export class TvSeasonAccountStates200ResponseResultsInner {
    'id'?: number = 0;
    'episode_number'?: number = 0;
    'rated'?: MovieAccountStates200ResponseRated;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "episode_number",
            "baseName": "episode_number",
            "type": "number"
        },
        {
            "name": "rated",
            "baseName": "rated",
            "type": "MovieAccountStates200ResponseRated"
        }    ];

    static getAttributeTypeMap() {
        return TvSeasonAccountStates200ResponseResultsInner.attributeTypeMap;
    }
}

