/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieWatchProviders200ResponseResultsBERentInner } from './movieWatchProviders200ResponseResultsBERentInner';
import { TvSeriesWatchProviders200ResponseResultsCAFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsCAFlatrateInner';

export class TvSeriesWatchProviders200ResponseResultsCA {
    'link'?: string;
    'buy'?: Array<MovieWatchProviders200ResponseResultsBERentInner>;
    'flatrate'?: Array<TvSeriesWatchProviders200ResponseResultsCAFlatrateInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<MovieWatchProviders200ResponseResultsBERentInner>"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsCAFlatrateInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesWatchProviders200ResponseResultsCA.attributeTypeMap;
    }
}

