/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieWatchProviders200ResponseResultsDEBuyInner } from './movieWatchProviders200ResponseResultsDEBuyInner';
import { TvSeriesWatchProviders200ResponseResultsBRFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsBRFlatrateInner';

export class TvSeasonWatchProviders200ResponseResultsUS {
    'link'?: string;
    'buy'?: Array<MovieWatchProviders200ResponseResultsDEBuyInner>;
    'free'?: Array<TvSeriesWatchProviders200ResponseResultsBRFlatrateInner>;
    'flatrate'?: Array<TvSeriesWatchProviders200ResponseResultsBRFlatrateInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<MovieWatchProviders200ResponseResultsDEBuyInner>"
        },
        {
            "name": "free",
            "baseName": "free",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsBRFlatrateInner>"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsBRFlatrateInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeasonWatchProviders200ResponseResultsUS.attributeTypeMap;
    }
}

