/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MovieWatchProviders200ResponseResultsSEBuyInner } from './movieWatchProviders200ResponseResultsSEBuyInner';
import { TvSeriesWatchProviders200ResponseResultsCRFlatrateInner } from './tvSeriesWatchProviders200ResponseResultsCRFlatrateInner';

export class TvSeriesWatchProviders200ResponseResultsSE {
    'link'?: string;
    'flatrate'?: Array<TvSeriesWatchProviders200ResponseResultsCRFlatrateInner>;
    'buy'?: Array<MovieWatchProviders200ResponseResultsSEBuyInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "flatrate",
            "baseName": "flatrate",
            "type": "Array<TvSeriesWatchProviders200ResponseResultsCRFlatrateInner>"
        },
        {
            "name": "buy",
            "baseName": "buy",
            "type": "Array<MovieWatchProviders200ResponseResultsSEBuyInner>"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesWatchProviders200ResponseResultsSE.attributeTypeMap;
    }
}

