/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TvSeasonWatchProviders200ResponseResultsAE } from './tvSeasonWatchProviders200ResponseResultsAE';
import { TvSeasonWatchProviders200ResponseResultsAR } from './tvSeasonWatchProviders200ResponseResultsAR';
import { TvSeasonWatchProviders200ResponseResultsAT } from './tvSeasonWatchProviders200ResponseResultsAT';
import { TvSeasonWatchProviders200ResponseResultsAU } from './tvSeasonWatchProviders200ResponseResultsAU';
import { TvSeasonWatchProviders200ResponseResultsBA } from './tvSeasonWatchProviders200ResponseResultsBA';
import { TvSeasonWatchProviders200ResponseResultsBB } from './tvSeasonWatchProviders200ResponseResultsBB';
import { TvSeasonWatchProviders200ResponseResultsBE } from './tvSeasonWatchProviders200ResponseResultsBE';
import { TvSeasonWatchProviders200ResponseResultsBG } from './tvSeasonWatchProviders200ResponseResultsBG';
import { TvSeasonWatchProviders200ResponseResultsBO } from './tvSeasonWatchProviders200ResponseResultsBO';
import { TvSeasonWatchProviders200ResponseResultsBR } from './tvSeasonWatchProviders200ResponseResultsBR';
import { TvSeasonWatchProviders200ResponseResultsBS } from './tvSeasonWatchProviders200ResponseResultsBS';
import { TvSeasonWatchProviders200ResponseResultsCA } from './tvSeasonWatchProviders200ResponseResultsCA';
import { TvSeasonWatchProviders200ResponseResultsCH } from './tvSeasonWatchProviders200ResponseResultsCH';
import { TvSeasonWatchProviders200ResponseResultsCI } from './tvSeasonWatchProviders200ResponseResultsCI';
import { TvSeasonWatchProviders200ResponseResultsCL } from './tvSeasonWatchProviders200ResponseResultsCL';
import { TvSeasonWatchProviders200ResponseResultsCO } from './tvSeasonWatchProviders200ResponseResultsCO';
import { TvSeasonWatchProviders200ResponseResultsCR } from './tvSeasonWatchProviders200ResponseResultsCR';
import { TvSeasonWatchProviders200ResponseResultsCZ } from './tvSeasonWatchProviders200ResponseResultsCZ';
import { TvSeasonWatchProviders200ResponseResultsDE } from './tvSeasonWatchProviders200ResponseResultsDE';
import { TvSeasonWatchProviders200ResponseResultsDK } from './tvSeasonWatchProviders200ResponseResultsDK';
import { TvSeasonWatchProviders200ResponseResultsDO } from './tvSeasonWatchProviders200ResponseResultsDO';
import { TvSeasonWatchProviders200ResponseResultsDZ } from './tvSeasonWatchProviders200ResponseResultsDZ';
import { TvSeasonWatchProviders200ResponseResultsEC } from './tvSeasonWatchProviders200ResponseResultsEC';
import { TvSeasonWatchProviders200ResponseResultsEG } from './tvSeasonWatchProviders200ResponseResultsEG';
import { TvSeasonWatchProviders200ResponseResultsES } from './tvSeasonWatchProviders200ResponseResultsES';
import { TvSeasonWatchProviders200ResponseResultsFI } from './tvSeasonWatchProviders200ResponseResultsFI';
import { TvSeasonWatchProviders200ResponseResultsFR } from './tvSeasonWatchProviders200ResponseResultsFR';
import { TvSeasonWatchProviders200ResponseResultsGB } from './tvSeasonWatchProviders200ResponseResultsGB';
import { TvSeasonWatchProviders200ResponseResultsGF } from './tvSeasonWatchProviders200ResponseResultsGF';
import { TvSeasonWatchProviders200ResponseResultsGH } from './tvSeasonWatchProviders200ResponseResultsGH';
import { TvSeasonWatchProviders200ResponseResultsGQ } from './tvSeasonWatchProviders200ResponseResultsGQ';
import { TvSeasonWatchProviders200ResponseResultsGT } from './tvSeasonWatchProviders200ResponseResultsGT';
import { TvSeasonWatchProviders200ResponseResultsHK } from './tvSeasonWatchProviders200ResponseResultsHK';
import { TvSeasonWatchProviders200ResponseResultsHN } from './tvSeasonWatchProviders200ResponseResultsHN';
import { TvSeasonWatchProviders200ResponseResultsHR } from './tvSeasonWatchProviders200ResponseResultsHR';
import { TvSeasonWatchProviders200ResponseResultsHU } from './tvSeasonWatchProviders200ResponseResultsHU';
import { TvSeasonWatchProviders200ResponseResultsID } from './tvSeasonWatchProviders200ResponseResultsID';
import { TvSeasonWatchProviders200ResponseResultsIE } from './tvSeasonWatchProviders200ResponseResultsIE';
import { TvSeasonWatchProviders200ResponseResultsIL } from './tvSeasonWatchProviders200ResponseResultsIL';
import { TvSeasonWatchProviders200ResponseResultsIQ } from './tvSeasonWatchProviders200ResponseResultsIQ';
import { TvSeasonWatchProviders200ResponseResultsIT } from './tvSeasonWatchProviders200ResponseResultsIT';
import { TvSeasonWatchProviders200ResponseResultsJM } from './tvSeasonWatchProviders200ResponseResultsJM';
import { TvSeasonWatchProviders200ResponseResultsJP } from './tvSeasonWatchProviders200ResponseResultsJP';
import { TvSeasonWatchProviders200ResponseResultsKE } from './tvSeasonWatchProviders200ResponseResultsKE';
import { TvSeasonWatchProviders200ResponseResultsKR } from './tvSeasonWatchProviders200ResponseResultsKR';
import { TvSeasonWatchProviders200ResponseResultsLB } from './tvSeasonWatchProviders200ResponseResultsLB';
import { TvSeasonWatchProviders200ResponseResultsLY } from './tvSeasonWatchProviders200ResponseResultsLY';
import { TvSeasonWatchProviders200ResponseResultsMD } from './tvSeasonWatchProviders200ResponseResultsMD';
import { TvSeasonWatchProviders200ResponseResultsMK } from './tvSeasonWatchProviders200ResponseResultsMK';
import { TvSeasonWatchProviders200ResponseResultsMU } from './tvSeasonWatchProviders200ResponseResultsMU';
import { TvSeasonWatchProviders200ResponseResultsMX } from './tvSeasonWatchProviders200ResponseResultsMX';
import { TvSeasonWatchProviders200ResponseResultsMY } from './tvSeasonWatchProviders200ResponseResultsMY';
import { TvSeasonWatchProviders200ResponseResultsMZ } from './tvSeasonWatchProviders200ResponseResultsMZ';
import { TvSeasonWatchProviders200ResponseResultsNE } from './tvSeasonWatchProviders200ResponseResultsNE';
import { TvSeasonWatchProviders200ResponseResultsNG } from './tvSeasonWatchProviders200ResponseResultsNG';
import { TvSeasonWatchProviders200ResponseResultsNL } from './tvSeasonWatchProviders200ResponseResultsNL';
import { TvSeasonWatchProviders200ResponseResultsNO } from './tvSeasonWatchProviders200ResponseResultsNO';
import { TvSeasonWatchProviders200ResponseResultsNZ } from './tvSeasonWatchProviders200ResponseResultsNZ';
import { TvSeasonWatchProviders200ResponseResultsPA } from './tvSeasonWatchProviders200ResponseResultsPA';
import { TvSeasonWatchProviders200ResponseResultsPE } from './tvSeasonWatchProviders200ResponseResultsPE';
import { TvSeasonWatchProviders200ResponseResultsPH } from './tvSeasonWatchProviders200ResponseResultsPH';
import { TvSeasonWatchProviders200ResponseResultsPL } from './tvSeasonWatchProviders200ResponseResultsPL';
import { TvSeasonWatchProviders200ResponseResultsPS } from './tvSeasonWatchProviders200ResponseResultsPS';
import { TvSeasonWatchProviders200ResponseResultsPT } from './tvSeasonWatchProviders200ResponseResultsPT';
import { TvSeasonWatchProviders200ResponseResultsPY } from './tvSeasonWatchProviders200ResponseResultsPY';
import { TvSeasonWatchProviders200ResponseResultsRO } from './tvSeasonWatchProviders200ResponseResultsRO';
import { TvSeasonWatchProviders200ResponseResultsRS } from './tvSeasonWatchProviders200ResponseResultsRS';
import { TvSeasonWatchProviders200ResponseResultsRU } from './tvSeasonWatchProviders200ResponseResultsRU';
import { TvSeasonWatchProviders200ResponseResultsSA } from './tvSeasonWatchProviders200ResponseResultsSA';
import { TvSeasonWatchProviders200ResponseResultsSC } from './tvSeasonWatchProviders200ResponseResultsSC';
import { TvSeasonWatchProviders200ResponseResultsSE } from './tvSeasonWatchProviders200ResponseResultsSE';
import { TvSeasonWatchProviders200ResponseResultsSG } from './tvSeasonWatchProviders200ResponseResultsSG';
import { TvSeasonWatchProviders200ResponseResultsSI } from './tvSeasonWatchProviders200ResponseResultsSI';
import { TvSeasonWatchProviders200ResponseResultsSK } from './tvSeasonWatchProviders200ResponseResultsSK';
import { TvSeasonWatchProviders200ResponseResultsSN } from './tvSeasonWatchProviders200ResponseResultsSN';
import { TvSeasonWatchProviders200ResponseResultsSV } from './tvSeasonWatchProviders200ResponseResultsSV';
import { TvSeasonWatchProviders200ResponseResultsTH } from './tvSeasonWatchProviders200ResponseResultsTH';
import { TvSeasonWatchProviders200ResponseResultsTR } from './tvSeasonWatchProviders200ResponseResultsTR';
import { TvSeasonWatchProviders200ResponseResultsTT } from './tvSeasonWatchProviders200ResponseResultsTT';
import { TvSeasonWatchProviders200ResponseResultsTW } from './tvSeasonWatchProviders200ResponseResultsTW';
import { TvSeasonWatchProviders200ResponseResultsTZ } from './tvSeasonWatchProviders200ResponseResultsTZ';
import { TvSeasonWatchProviders200ResponseResultsUG } from './tvSeasonWatchProviders200ResponseResultsUG';
import { TvSeasonWatchProviders200ResponseResultsUS } from './tvSeasonWatchProviders200ResponseResultsUS';
import { TvSeasonWatchProviders200ResponseResultsUY } from './tvSeasonWatchProviders200ResponseResultsUY';
import { TvSeasonWatchProviders200ResponseResultsVE } from './tvSeasonWatchProviders200ResponseResultsVE';
import { TvSeasonWatchProviders200ResponseResultsZA } from './tvSeasonWatchProviders200ResponseResultsZA';
import { TvSeasonWatchProviders200ResponseResultsZM } from './tvSeasonWatchProviders200ResponseResultsZM';

export class TvSeasonWatchProviders200ResponseResults {
    'AE'?: TvSeasonWatchProviders200ResponseResultsAE;
    'AR'?: TvSeasonWatchProviders200ResponseResultsAR;
    'AT'?: TvSeasonWatchProviders200ResponseResultsAT;
    'AU'?: TvSeasonWatchProviders200ResponseResultsAU;
    'BA'?: TvSeasonWatchProviders200ResponseResultsBA;
    'BB'?: TvSeasonWatchProviders200ResponseResultsBB;
    'BE'?: TvSeasonWatchProviders200ResponseResultsBE;
    'BG'?: TvSeasonWatchProviders200ResponseResultsBG;
    'BO'?: TvSeasonWatchProviders200ResponseResultsBO;
    'BR'?: TvSeasonWatchProviders200ResponseResultsBR;
    'BS'?: TvSeasonWatchProviders200ResponseResultsBS;
    'CA'?: TvSeasonWatchProviders200ResponseResultsCA;
    'CH'?: TvSeasonWatchProviders200ResponseResultsCH;
    'CI'?: TvSeasonWatchProviders200ResponseResultsCI;
    'CL'?: TvSeasonWatchProviders200ResponseResultsCL;
    'CO'?: TvSeasonWatchProviders200ResponseResultsCO;
    'CR'?: TvSeasonWatchProviders200ResponseResultsCR;
    'CZ'?: TvSeasonWatchProviders200ResponseResultsCZ;
    'DE'?: TvSeasonWatchProviders200ResponseResultsDE;
    'DK'?: TvSeasonWatchProviders200ResponseResultsDK;
    'DO'?: TvSeasonWatchProviders200ResponseResultsDO;
    'DZ'?: TvSeasonWatchProviders200ResponseResultsDZ;
    'EC'?: TvSeasonWatchProviders200ResponseResultsEC;
    'EG'?: TvSeasonWatchProviders200ResponseResultsEG;
    'ES'?: TvSeasonWatchProviders200ResponseResultsES;
    'FI'?: TvSeasonWatchProviders200ResponseResultsFI;
    'FR'?: TvSeasonWatchProviders200ResponseResultsFR;
    'GB'?: TvSeasonWatchProviders200ResponseResultsGB;
    'GF'?: TvSeasonWatchProviders200ResponseResultsGF;
    'GH'?: TvSeasonWatchProviders200ResponseResultsGH;
    'GQ'?: TvSeasonWatchProviders200ResponseResultsGQ;
    'GT'?: TvSeasonWatchProviders200ResponseResultsGT;
    'HK'?: TvSeasonWatchProviders200ResponseResultsHK;
    'HN'?: TvSeasonWatchProviders200ResponseResultsHN;
    'HR'?: TvSeasonWatchProviders200ResponseResultsHR;
    'HU'?: TvSeasonWatchProviders200ResponseResultsHU;
    'ID'?: TvSeasonWatchProviders200ResponseResultsID;
    'IE'?: TvSeasonWatchProviders200ResponseResultsIE;
    'IL'?: TvSeasonWatchProviders200ResponseResultsIL;
    'IQ'?: TvSeasonWatchProviders200ResponseResultsIQ;
    'IT'?: TvSeasonWatchProviders200ResponseResultsIT;
    'JM'?: TvSeasonWatchProviders200ResponseResultsJM;
    'JP'?: TvSeasonWatchProviders200ResponseResultsJP;
    'KE'?: TvSeasonWatchProviders200ResponseResultsKE;
    'KR'?: TvSeasonWatchProviders200ResponseResultsKR;
    'LB'?: TvSeasonWatchProviders200ResponseResultsLB;
    'LY'?: TvSeasonWatchProviders200ResponseResultsLY;
    'MD'?: TvSeasonWatchProviders200ResponseResultsMD;
    'MK'?: TvSeasonWatchProviders200ResponseResultsMK;
    'MU'?: TvSeasonWatchProviders200ResponseResultsMU;
    'MX'?: TvSeasonWatchProviders200ResponseResultsMX;
    'MY'?: TvSeasonWatchProviders200ResponseResultsMY;
    'MZ'?: TvSeasonWatchProviders200ResponseResultsMZ;
    'NE'?: TvSeasonWatchProviders200ResponseResultsNE;
    'NG'?: TvSeasonWatchProviders200ResponseResultsNG;
    'NL'?: TvSeasonWatchProviders200ResponseResultsNL;
    'NO'?: TvSeasonWatchProviders200ResponseResultsNO;
    'NZ'?: TvSeasonWatchProviders200ResponseResultsNZ;
    'PA'?: TvSeasonWatchProviders200ResponseResultsPA;
    'PE'?: TvSeasonWatchProviders200ResponseResultsPE;
    'PH'?: TvSeasonWatchProviders200ResponseResultsPH;
    'PL'?: TvSeasonWatchProviders200ResponseResultsPL;
    'PS'?: TvSeasonWatchProviders200ResponseResultsPS;
    'PT'?: TvSeasonWatchProviders200ResponseResultsPT;
    'PY'?: TvSeasonWatchProviders200ResponseResultsPY;
    'RO'?: TvSeasonWatchProviders200ResponseResultsRO;
    'RS'?: TvSeasonWatchProviders200ResponseResultsRS;
    'RU'?: TvSeasonWatchProviders200ResponseResultsRU;
    'SA'?: TvSeasonWatchProviders200ResponseResultsSA;
    'SC'?: TvSeasonWatchProviders200ResponseResultsSC;
    'SE'?: TvSeasonWatchProviders200ResponseResultsSE;
    'SG'?: TvSeasonWatchProviders200ResponseResultsSG;
    'SI'?: TvSeasonWatchProviders200ResponseResultsSI;
    'SK'?: TvSeasonWatchProviders200ResponseResultsSK;
    'SN'?: TvSeasonWatchProviders200ResponseResultsSN;
    'SV'?: TvSeasonWatchProviders200ResponseResultsSV;
    'TH'?: TvSeasonWatchProviders200ResponseResultsTH;
    'TR'?: TvSeasonWatchProviders200ResponseResultsTR;
    'TT'?: TvSeasonWatchProviders200ResponseResultsTT;
    'TW'?: TvSeasonWatchProviders200ResponseResultsTW;
    'TZ'?: TvSeasonWatchProviders200ResponseResultsTZ;
    'UG'?: TvSeasonWatchProviders200ResponseResultsUG;
    'US'?: TvSeasonWatchProviders200ResponseResultsUS;
    'UY'?: TvSeasonWatchProviders200ResponseResultsUY;
    'VE'?: TvSeasonWatchProviders200ResponseResultsVE;
    'ZA'?: TvSeasonWatchProviders200ResponseResultsZA;
    'ZM'?: TvSeasonWatchProviders200ResponseResultsZM;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "AE",
            "baseName": "AE",
            "type": "TvSeasonWatchProviders200ResponseResultsAE"
        },
        {
            "name": "AR",
            "baseName": "AR",
            "type": "TvSeasonWatchProviders200ResponseResultsAR"
        },
        {
            "name": "AT",
            "baseName": "AT",
            "type": "TvSeasonWatchProviders200ResponseResultsAT"
        },
        {
            "name": "AU",
            "baseName": "AU",
            "type": "TvSeasonWatchProviders200ResponseResultsAU"
        },
        {
            "name": "BA",
            "baseName": "BA",
            "type": "TvSeasonWatchProviders200ResponseResultsBA"
        },
        {
            "name": "BB",
            "baseName": "BB",
            "type": "TvSeasonWatchProviders200ResponseResultsBB"
        },
        {
            "name": "BE",
            "baseName": "BE",
            "type": "TvSeasonWatchProviders200ResponseResultsBE"
        },
        {
            "name": "BG",
            "baseName": "BG",
            "type": "TvSeasonWatchProviders200ResponseResultsBG"
        },
        {
            "name": "BO",
            "baseName": "BO",
            "type": "TvSeasonWatchProviders200ResponseResultsBO"
        },
        {
            "name": "BR",
            "baseName": "BR",
            "type": "TvSeasonWatchProviders200ResponseResultsBR"
        },
        {
            "name": "BS",
            "baseName": "BS",
            "type": "TvSeasonWatchProviders200ResponseResultsBS"
        },
        {
            "name": "CA",
            "baseName": "CA",
            "type": "TvSeasonWatchProviders200ResponseResultsCA"
        },
        {
            "name": "CH",
            "baseName": "CH",
            "type": "TvSeasonWatchProviders200ResponseResultsCH"
        },
        {
            "name": "CI",
            "baseName": "CI",
            "type": "TvSeasonWatchProviders200ResponseResultsCI"
        },
        {
            "name": "CL",
            "baseName": "CL",
            "type": "TvSeasonWatchProviders200ResponseResultsCL"
        },
        {
            "name": "CO",
            "baseName": "CO",
            "type": "TvSeasonWatchProviders200ResponseResultsCO"
        },
        {
            "name": "CR",
            "baseName": "CR",
            "type": "TvSeasonWatchProviders200ResponseResultsCR"
        },
        {
            "name": "CZ",
            "baseName": "CZ",
            "type": "TvSeasonWatchProviders200ResponseResultsCZ"
        },
        {
            "name": "DE",
            "baseName": "DE",
            "type": "TvSeasonWatchProviders200ResponseResultsDE"
        },
        {
            "name": "DK",
            "baseName": "DK",
            "type": "TvSeasonWatchProviders200ResponseResultsDK"
        },
        {
            "name": "DO",
            "baseName": "DO",
            "type": "TvSeasonWatchProviders200ResponseResultsDO"
        },
        {
            "name": "DZ",
            "baseName": "DZ",
            "type": "TvSeasonWatchProviders200ResponseResultsDZ"
        },
        {
            "name": "EC",
            "baseName": "EC",
            "type": "TvSeasonWatchProviders200ResponseResultsEC"
        },
        {
            "name": "EG",
            "baseName": "EG",
            "type": "TvSeasonWatchProviders200ResponseResultsEG"
        },
        {
            "name": "ES",
            "baseName": "ES",
            "type": "TvSeasonWatchProviders200ResponseResultsES"
        },
        {
            "name": "FI",
            "baseName": "FI",
            "type": "TvSeasonWatchProviders200ResponseResultsFI"
        },
        {
            "name": "FR",
            "baseName": "FR",
            "type": "TvSeasonWatchProviders200ResponseResultsFR"
        },
        {
            "name": "GB",
            "baseName": "GB",
            "type": "TvSeasonWatchProviders200ResponseResultsGB"
        },
        {
            "name": "GF",
            "baseName": "GF",
            "type": "TvSeasonWatchProviders200ResponseResultsGF"
        },
        {
            "name": "GH",
            "baseName": "GH",
            "type": "TvSeasonWatchProviders200ResponseResultsGH"
        },
        {
            "name": "GQ",
            "baseName": "GQ",
            "type": "TvSeasonWatchProviders200ResponseResultsGQ"
        },
        {
            "name": "GT",
            "baseName": "GT",
            "type": "TvSeasonWatchProviders200ResponseResultsGT"
        },
        {
            "name": "HK",
            "baseName": "HK",
            "type": "TvSeasonWatchProviders200ResponseResultsHK"
        },
        {
            "name": "HN",
            "baseName": "HN",
            "type": "TvSeasonWatchProviders200ResponseResultsHN"
        },
        {
            "name": "HR",
            "baseName": "HR",
            "type": "TvSeasonWatchProviders200ResponseResultsHR"
        },
        {
            "name": "HU",
            "baseName": "HU",
            "type": "TvSeasonWatchProviders200ResponseResultsHU"
        },
        {
            "name": "ID",
            "baseName": "ID",
            "type": "TvSeasonWatchProviders200ResponseResultsID"
        },
        {
            "name": "IE",
            "baseName": "IE",
            "type": "TvSeasonWatchProviders200ResponseResultsIE"
        },
        {
            "name": "IL",
            "baseName": "IL",
            "type": "TvSeasonWatchProviders200ResponseResultsIL"
        },
        {
            "name": "IQ",
            "baseName": "IQ",
            "type": "TvSeasonWatchProviders200ResponseResultsIQ"
        },
        {
            "name": "IT",
            "baseName": "IT",
            "type": "TvSeasonWatchProviders200ResponseResultsIT"
        },
        {
            "name": "JM",
            "baseName": "JM",
            "type": "TvSeasonWatchProviders200ResponseResultsJM"
        },
        {
            "name": "JP",
            "baseName": "JP",
            "type": "TvSeasonWatchProviders200ResponseResultsJP"
        },
        {
            "name": "KE",
            "baseName": "KE",
            "type": "TvSeasonWatchProviders200ResponseResultsKE"
        },
        {
            "name": "KR",
            "baseName": "KR",
            "type": "TvSeasonWatchProviders200ResponseResultsKR"
        },
        {
            "name": "LB",
            "baseName": "LB",
            "type": "TvSeasonWatchProviders200ResponseResultsLB"
        },
        {
            "name": "LY",
            "baseName": "LY",
            "type": "TvSeasonWatchProviders200ResponseResultsLY"
        },
        {
            "name": "MD",
            "baseName": "MD",
            "type": "TvSeasonWatchProviders200ResponseResultsMD"
        },
        {
            "name": "MK",
            "baseName": "MK",
            "type": "TvSeasonWatchProviders200ResponseResultsMK"
        },
        {
            "name": "MU",
            "baseName": "MU",
            "type": "TvSeasonWatchProviders200ResponseResultsMU"
        },
        {
            "name": "MX",
            "baseName": "MX",
            "type": "TvSeasonWatchProviders200ResponseResultsMX"
        },
        {
            "name": "MY",
            "baseName": "MY",
            "type": "TvSeasonWatchProviders200ResponseResultsMY"
        },
        {
            "name": "MZ",
            "baseName": "MZ",
            "type": "TvSeasonWatchProviders200ResponseResultsMZ"
        },
        {
            "name": "NE",
            "baseName": "NE",
            "type": "TvSeasonWatchProviders200ResponseResultsNE"
        },
        {
            "name": "NG",
            "baseName": "NG",
            "type": "TvSeasonWatchProviders200ResponseResultsNG"
        },
        {
            "name": "NL",
            "baseName": "NL",
            "type": "TvSeasonWatchProviders200ResponseResultsNL"
        },
        {
            "name": "NO",
            "baseName": "NO",
            "type": "TvSeasonWatchProviders200ResponseResultsNO"
        },
        {
            "name": "NZ",
            "baseName": "NZ",
            "type": "TvSeasonWatchProviders200ResponseResultsNZ"
        },
        {
            "name": "PA",
            "baseName": "PA",
            "type": "TvSeasonWatchProviders200ResponseResultsPA"
        },
        {
            "name": "PE",
            "baseName": "PE",
            "type": "TvSeasonWatchProviders200ResponseResultsPE"
        },
        {
            "name": "PH",
            "baseName": "PH",
            "type": "TvSeasonWatchProviders200ResponseResultsPH"
        },
        {
            "name": "PL",
            "baseName": "PL",
            "type": "TvSeasonWatchProviders200ResponseResultsPL"
        },
        {
            "name": "PS",
            "baseName": "PS",
            "type": "TvSeasonWatchProviders200ResponseResultsPS"
        },
        {
            "name": "PT",
            "baseName": "PT",
            "type": "TvSeasonWatchProviders200ResponseResultsPT"
        },
        {
            "name": "PY",
            "baseName": "PY",
            "type": "TvSeasonWatchProviders200ResponseResultsPY"
        },
        {
            "name": "RO",
            "baseName": "RO",
            "type": "TvSeasonWatchProviders200ResponseResultsRO"
        },
        {
            "name": "RS",
            "baseName": "RS",
            "type": "TvSeasonWatchProviders200ResponseResultsRS"
        },
        {
            "name": "RU",
            "baseName": "RU",
            "type": "TvSeasonWatchProviders200ResponseResultsRU"
        },
        {
            "name": "SA",
            "baseName": "SA",
            "type": "TvSeasonWatchProviders200ResponseResultsSA"
        },
        {
            "name": "SC",
            "baseName": "SC",
            "type": "TvSeasonWatchProviders200ResponseResultsSC"
        },
        {
            "name": "SE",
            "baseName": "SE",
            "type": "TvSeasonWatchProviders200ResponseResultsSE"
        },
        {
            "name": "SG",
            "baseName": "SG",
            "type": "TvSeasonWatchProviders200ResponseResultsSG"
        },
        {
            "name": "SI",
            "baseName": "SI",
            "type": "TvSeasonWatchProviders200ResponseResultsSI"
        },
        {
            "name": "SK",
            "baseName": "SK",
            "type": "TvSeasonWatchProviders200ResponseResultsSK"
        },
        {
            "name": "SN",
            "baseName": "SN",
            "type": "TvSeasonWatchProviders200ResponseResultsSN"
        },
        {
            "name": "SV",
            "baseName": "SV",
            "type": "TvSeasonWatchProviders200ResponseResultsSV"
        },
        {
            "name": "TH",
            "baseName": "TH",
            "type": "TvSeasonWatchProviders200ResponseResultsTH"
        },
        {
            "name": "TR",
            "baseName": "TR",
            "type": "TvSeasonWatchProviders200ResponseResultsTR"
        },
        {
            "name": "TT",
            "baseName": "TT",
            "type": "TvSeasonWatchProviders200ResponseResultsTT"
        },
        {
            "name": "TW",
            "baseName": "TW",
            "type": "TvSeasonWatchProviders200ResponseResultsTW"
        },
        {
            "name": "TZ",
            "baseName": "TZ",
            "type": "TvSeasonWatchProviders200ResponseResultsTZ"
        },
        {
            "name": "UG",
            "baseName": "UG",
            "type": "TvSeasonWatchProviders200ResponseResultsUG"
        },
        {
            "name": "US",
            "baseName": "US",
            "type": "TvSeasonWatchProviders200ResponseResultsUS"
        },
        {
            "name": "UY",
            "baseName": "UY",
            "type": "TvSeasonWatchProviders200ResponseResultsUY"
        },
        {
            "name": "VE",
            "baseName": "VE",
            "type": "TvSeasonWatchProviders200ResponseResultsVE"
        },
        {
            "name": "ZA",
            "baseName": "ZA",
            "type": "TvSeasonWatchProviders200ResponseResultsZA"
        },
        {
            "name": "ZM",
            "baseName": "ZM",
            "type": "TvSeasonWatchProviders200ResponseResultsZM"
        }    ];

    static getAttributeTypeMap() {
        return TvSeasonWatchProviders200ResponseResults.attributeTypeMap;
    }
}

