/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TvSeriesTranslations200ResponseTranslationsInnerData {
    'name'?: string;
    'overview'?: string;
    'homepage'?: string;
    'tagline'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "overview",
            "baseName": "overview",
            "type": "string"
        },
        {
            "name": "homepage",
            "baseName": "homepage",
            "type": "string"
        },
        {
            "name": "tagline",
            "baseName": "tagline",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesTranslations200ResponseTranslationsInnerData.attributeTypeMap;
    }
}

