/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TvSeriesScreenedTheatrically200ResponseResultsInner {
    'id'?: number = 0;
    'episode_number'?: number = 0;
    'season_number'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "episode_number",
            "baseName": "episode_number",
            "type": "number"
        },
        {
            "name": "season_number",
            "baseName": "season_number",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return TvSeriesScreenedTheatrically200ResponseResultsInner.attributeTypeMap;
    }
}

