/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class WatchProvidersMovieList200ResponseResultsInnerDisplayPriorities {
    'CA'?: number = 0;
    'AE'?: number = 0;
    'AR'?: number = 0;
    'AT'?: number = 0;
    'AU'?: number = 0;
    'BE'?: number = 0;
    'BO'?: number = 0;
    'BR'?: number = 0;
    'BG'?: number = 0;
    'CH'?: number = 0;
    'CL'?: number = 0;
    'CO'?: number = 0;
    'CR'?: number = 0;
    'CZ'?: number = 0;
    'DE'?: number = 0;
    'DK'?: number = 0;
    'EC'?: number = 0;
    'EE'?: number = 0;
    'EG'?: number = 0;
    'ES'?: number = 0;
    'FI'?: number = 0;
    'FR'?: number = 0;
    'GB'?: number = 0;
    'GR'?: number = 0;
    'GT'?: number = 0;
    'HK'?: number = 0;
    'HN'?: number = 0;
    'HU'?: number = 0;
    'ID'?: number = 0;
    'IE'?: number = 0;
    'IN'?: number = 0;
    'IT'?: number = 0;
    'JP'?: number = 0;
    'LT'?: number = 0;
    'LV'?: number = 0;
    'MX'?: number = 0;
    'MY'?: number = 0;
    'NL'?: number = 0;
    'NO'?: number = 0;
    'NZ'?: number = 0;
    'PE'?: number = 0;
    'PH'?: number = 0;
    'PL'?: number = 0;
    'PT'?: number = 0;
    'PY'?: number = 0;
    'RU'?: number = 0;
    'SA'?: number = 0;
    'SE'?: number = 0;
    'SG'?: number = 0;
    'SK'?: number = 0;
    'TH'?: number = 0;
    'TR'?: number = 0;
    'TW'?: number = 0;
    'US'?: number = 0;
    'VE'?: number = 0;
    'ZA'?: number = 0;
    'SI'?: number = 0;
    'CV'?: number = 0;
    'GH'?: number = 0;
    'MU'?: number = 0;
    'MZ'?: number = 0;
    'UG'?: number = 0;
    'IL'?: number = 0;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "CA",
            "baseName": "CA",
            "type": "number"
        },
        {
            "name": "AE",
            "baseName": "AE",
            "type": "number"
        },
        {
            "name": "AR",
            "baseName": "AR",
            "type": "number"
        },
        {
            "name": "AT",
            "baseName": "AT",
            "type": "number"
        },
        {
            "name": "AU",
            "baseName": "AU",
            "type": "number"
        },
        {
            "name": "BE",
            "baseName": "BE",
            "type": "number"
        },
        {
            "name": "BO",
            "baseName": "BO",
            "type": "number"
        },
        {
            "name": "BR",
            "baseName": "BR",
            "type": "number"
        },
        {
            "name": "BG",
            "baseName": "BG",
            "type": "number"
        },
        {
            "name": "CH",
            "baseName": "CH",
            "type": "number"
        },
        {
            "name": "CL",
            "baseName": "CL",
            "type": "number"
        },
        {
            "name": "CO",
            "baseName": "CO",
            "type": "number"
        },
        {
            "name": "CR",
            "baseName": "CR",
            "type": "number"
        },
        {
            "name": "CZ",
            "baseName": "CZ",
            "type": "number"
        },
        {
            "name": "DE",
            "baseName": "DE",
            "type": "number"
        },
        {
            "name": "DK",
            "baseName": "DK",
            "type": "number"
        },
        {
            "name": "EC",
            "baseName": "EC",
            "type": "number"
        },
        {
            "name": "EE",
            "baseName": "EE",
            "type": "number"
        },
        {
            "name": "EG",
            "baseName": "EG",
            "type": "number"
        },
        {
            "name": "ES",
            "baseName": "ES",
            "type": "number"
        },
        {
            "name": "FI",
            "baseName": "FI",
            "type": "number"
        },
        {
            "name": "FR",
            "baseName": "FR",
            "type": "number"
        },
        {
            "name": "GB",
            "baseName": "GB",
            "type": "number"
        },
        {
            "name": "GR",
            "baseName": "GR",
            "type": "number"
        },
        {
            "name": "GT",
            "baseName": "GT",
            "type": "number"
        },
        {
            "name": "HK",
            "baseName": "HK",
            "type": "number"
        },
        {
            "name": "HN",
            "baseName": "HN",
            "type": "number"
        },
        {
            "name": "HU",
            "baseName": "HU",
            "type": "number"
        },
        {
            "name": "ID",
            "baseName": "ID",
            "type": "number"
        },
        {
            "name": "IE",
            "baseName": "IE",
            "type": "number"
        },
        {
            "name": "IN",
            "baseName": "IN",
            "type": "number"
        },
        {
            "name": "IT",
            "baseName": "IT",
            "type": "number"
        },
        {
            "name": "JP",
            "baseName": "JP",
            "type": "number"
        },
        {
            "name": "LT",
            "baseName": "LT",
            "type": "number"
        },
        {
            "name": "LV",
            "baseName": "LV",
            "type": "number"
        },
        {
            "name": "MX",
            "baseName": "MX",
            "type": "number"
        },
        {
            "name": "MY",
            "baseName": "MY",
            "type": "number"
        },
        {
            "name": "NL",
            "baseName": "NL",
            "type": "number"
        },
        {
            "name": "NO",
            "baseName": "NO",
            "type": "number"
        },
        {
            "name": "NZ",
            "baseName": "NZ",
            "type": "number"
        },
        {
            "name": "PE",
            "baseName": "PE",
            "type": "number"
        },
        {
            "name": "PH",
            "baseName": "PH",
            "type": "number"
        },
        {
            "name": "PL",
            "baseName": "PL",
            "type": "number"
        },
        {
            "name": "PT",
            "baseName": "PT",
            "type": "number"
        },
        {
            "name": "PY",
            "baseName": "PY",
            "type": "number"
        },
        {
            "name": "RU",
            "baseName": "RU",
            "type": "number"
        },
        {
            "name": "SA",
            "baseName": "SA",
            "type": "number"
        },
        {
            "name": "SE",
            "baseName": "SE",
            "type": "number"
        },
        {
            "name": "SG",
            "baseName": "SG",
            "type": "number"
        },
        {
            "name": "SK",
            "baseName": "SK",
            "type": "number"
        },
        {
            "name": "TH",
            "baseName": "TH",
            "type": "number"
        },
        {
            "name": "TR",
            "baseName": "TR",
            "type": "number"
        },
        {
            "name": "TW",
            "baseName": "TW",
            "type": "number"
        },
        {
            "name": "US",
            "baseName": "US",
            "type": "number"
        },
        {
            "name": "VE",
            "baseName": "VE",
            "type": "number"
        },
        {
            "name": "ZA",
            "baseName": "ZA",
            "type": "number"
        },
        {
            "name": "SI",
            "baseName": "SI",
            "type": "number"
        },
        {
            "name": "CV",
            "baseName": "CV",
            "type": "number"
        },
        {
            "name": "GH",
            "baseName": "GH",
            "type": "number"
        },
        {
            "name": "MU",
            "baseName": "MU",
            "type": "number"
        },
        {
            "name": "MZ",
            "baseName": "MZ",
            "type": "number"
        },
        {
            "name": "UG",
            "baseName": "UG",
            "type": "number"
        },
        {
            "name": "IL",
            "baseName": "IL",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return WatchProvidersMovieList200ResponseResultsInnerDisplayPriorities.attributeTypeMap;
    }
}

