/**
 * TMDB API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { WatchProvidersAvailableRegions200ResponseResultsInner } from './watchProvidersAvailableRegions200ResponseResultsInner';

export class WatchProvidersAvailableRegions200Response {
    'results'?: Array<WatchProvidersAvailableRegions200ResponseResultsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<WatchProvidersAvailableRegions200ResponseResultsInner>"
        }    ];

    static getAttributeTypeMap() {
        return WatchProvidersAvailableRegions200Response.attributeTypeMap;
    }
}

